In [ ]:
#Python Collection DataTypes 
    #Lists
    #Tuple
    #Dictionaries
    #Sets 
#Break 
#Loops in Python 
    #For Loop
    #While 
    #If and Else 

#Numpy
#Arrays 
#Matrix
#Will See
    #DataFrame 

In [81]:
myfirstlist = [21,22,34,32,22,21,11,24,33,22,33,43,44,33,44]

In [3]:
type(myfirstlist)

list

In [4]:
len(myfirstlist)

15

In [5]:
myfirstlist[4]

22

In [8]:
myfirstlist[4:10]

[22, 21, 11, 24, 33, 22]

In [9]:
myfirstlist[4:]

[22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44]

In [10]:
myfirstlist[:5]

[21, 22, 34, 32, 22]

In [12]:
myfirstlist[-1]

44

In [14]:
myfirstlist[:5]

[21, 22, 34, 32, 22]

In [21]:
myfirstlist

[21, 22, 34, 32, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44]

In [22]:
myfirstlist[-1:-9]

[]

In [24]:
myfirstlist[-1:-9:-1]

[44, 33, 44, 43, 33, 22, 33, 24]

In [26]:
myfirstlist

[21, 22, 34, 32, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44]

In [27]:
myfirstlist[-1:-10:-2]

[44, 44, 33, 33, 11]

In [37]:
mylist = ['Rahul',33, 'Shilpi', 32, 'Atharv', 6, 'Roli', 36, 'True']

In [38]:
type(mylist[-1])

str

In [39]:
languages = [['English', 'Hindi'], ['Spanish'], 'French', 'English', ['Hindi', 'Spanish']]

In [52]:
languages[0][0]

'English'

In [50]:
list(languages[0])

['English', 'Hindi']

In [54]:
myfirstlist.append(100)

In [55]:
myfirstlist

[21, 22, 34, 32, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44, 100]

In [56]:
myfirstlist.insert(4,0)

In [57]:
myfirstlist

[21, 22, 34, 32, 0, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44, 100]

In [58]:
mylist2 = myfirstlist.copy()

In [59]:
mylist2

[21, 22, 34, 32, 0, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44, 100]

In [60]:
myfirstlist.count(22)

3

In [62]:
myfirstlist.index(0)

4

In [63]:
myfirstlist.pop(0)

21

In [64]:
myfirstlist

[22, 34, 32, 0, 22, 21, 11, 24, 33, 22, 33, 43, 44, 33, 44, 100]

In [65]:
help(myfirstlist.index)

Help on built-in function index:

index(...) method of builtins.list instance
    L.index(value, [start, [stop]]) -> integer -- return first index of value.
    Raises ValueError if the value is not present.



In [66]:
myfirstlist.sort()

In [67]:
myfirstlist

[0, 11, 21, 22, 22, 22, 24, 32, 33, 33, 33, 34, 43, 44, 44, 100]

In [68]:
myfirstlist.reverse()

In [69]:
myfirstlist

[100, 44, 44, 43, 34, 33, 33, 33, 32, 24, 22, 22, 22, 21, 11, 0]

In [70]:
max(myfirstlist)

100

In [71]:
min(myfirstlist)

0

In [72]:
del mylist

In [73]:
myfirstlist.clear()

In [74]:
myfirstlist

[]

In [76]:
mylist2[0]=1000

In [78]:
del mylist2

In [80]:
del myfirstlist

In [83]:
myfirsttuple = (21,32,33,43,44,33,23,22,33,24)

In [84]:
myfirsttuple[0]=1000

TypeError: 'tuple' object does not support item assignment

In [85]:
type(myfirsttuple)

tuple

In [88]:
myfirsttuple.count(33)

3

In [89]:
myfirsttuple.index(33)

2

In [91]:
myfirsttuple[4:7]

(44, 33, 23)

In [92]:
mytup = (1,2,3,[4,5,6])

In [93]:
type(mytup)

tuple

In [95]:
type(mytup[3])

list

In [97]:
mytup[3][0]=0

In [98]:
mytup

(1, 2, 3, [0, 5, 6])

# Dictionaries

In [99]:
myfirstdict = {'customer_name':'John', 'Order_id':1234, 'Region':'North'}

In [102]:
myfirstdict['segment']='Python'

In [103]:
myfirstdict

{'customer_name': 'John',
 'Order_id': 1234,
 'Region': 'North',
 'segment': 'Python'}

In [104]:
myfirstdict['OID']= myfirstdict.pop('Order_id')

In [105]:
myfirstdict

{'customer_name': 'John', 'Region': 'North', 'segment': 'Python', 'OID': 1234}

In [113]:
my_stud = {'student_id': [1,2,3,4,5,6],
          'student_id':['A','B','C','D','E','F'],
          'Subject':['Python','Tableau','Tableau','PowerBI','AWS','R']}

In [114]:
my_stud

{'student_id': ['A', 'B', 'C', 'D', 'E', 'F'],
 'Subject': ['Python', 'Tableau', 'Tableau', 'PowerBI', 'AWS', 'R']}

In [109]:
my_stud['stud_name']

['A', 'B', 'C', 'D', 'E', 'F']

In [110]:
import pandas as pd

In [111]:
pd.DataFrame(my_stud)

student_id stud_name  Subject
0           1         A   Python
1           2         B  Tableau
2           3         C  Tableau
3           4         D  PowerBI
4           5         E      AWS
5           6         F        R

In [112]:
dict(([1,2],[1,4],[3,6]))

{1: 4, 3: 6}

In [116]:
my_stud.keys()

dict_keys(['student_id', 'Subject'])

In [117]:
my_stud.values()

dict_values([['A', 'B', 'C', 'D', 'E', 'F'], ['Python', 'Tableau', 'Tableau', 'PowerBI', 'AWS', 'R']])

In [118]:
my_stud.popitem()

('Subject', ['Python', 'Tableau', 'Tableau', 'PowerBI', 'AWS', 'R'])

In [125]:
my_stud.pop('student_id')

['A', 'B', 'C', 'D', 'E', 'F']

In [126]:
my_stud

{}

In [130]:
dict1 = {1:1,2:5}
dict2 = {2:2,3:3}

In [121]:
dict1

{1: 1, 2: 5}

In [122]:
dict2

{4: 2, 3: 3}

In [134]:
dict1.

dict_items([(1, 1), (2, 2), (3, 3)])

In [131]:
dict1.update(dict2)

In [132]:
dict1

{1: 1, 2: 2, 3: 3}

# Sets dvsdfd

In [135]:
myfirstset = {1,2,2,2,2,3,3,3,4,5}

In [140]:
myfirstset.add(40)

In [141]:
myfirstset

{1, 2, 3, 4, 5, 40}

In [144]:
myfirstset.update((40,41,41,41,41,42))

In [171]:
myfirstset[0]=30

TypeError: 'set' object does not support item assignment

In [147]:
set([1,2,2,3])

{1, 2, 3}

In [178]:
myfirstset.remove(3)

KeyError: 3

In [186]:
myfirstset.discard(4)

In [172]:
myfirstset.pop()

1

In [173]:
myfirstset

{2, 5, 40, 41, 42}

In [174]:
myset1 = {1,2,2,3}
myset2 = {2,3,3,4}

In [175]:
myset1.union(myset2)

{1, 2, 3, 4}

In [176]:
myset1.intersection(myset2)

{2, 3}

In [187]:
myset1.difference(myset2)

{1}

In [188]:
myset1

{1, 2, 3}

In [189]:
myfirstlist = [21,22,34,32,22,21,11,24,33,22,33,43,44,33,44]

In [190]:
myfirstlist[-1:5:-1]

[44, 33, 44, 43, 33, 22, 33, 24, 11]

# Loops and conditional statements

In [ ]:
#Traditional programming
for condition {
    statement1
    statement2
}
statement3

#Python Programming
for condition:
    statement1
    statement2
statement3

In [196]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
mylist = []

In [199]:
for i in range(0,4):
    print('Hi')
    print('Hello')

Hi
Hello
Hi
Hello
Hi
Hello
Hi
Hello


In [209]:
customer = ('A','B','C','D','E','F')
orderid = (1,2,3,4,5,6,7)

In [212]:
for (c,o) in zip(customer,orderid):
    print('hi')
print('Hello'," ", c, 'your order id is:', o)

hi
hi
hi
hi
hi
hi
Hello   F your order id is: 6


In [ ]:
while condition{
    statement1
    statement2
}
statement3



while condition:
    statement1
    statement2
statement3

In [218]:
counter = 0
while counter<6:
    print(counter)
    counter+=1
print('Hi')

0
1
2
3
4
5
Hi


In [219]:
coupouns = 5
utilized = 0
while utilized<6:
    print('Total coupouns left are:', coupouns-utilized)
    utilized=utilized+1
print('No counpouns left')

Total coupouns left are: 5
Total coupouns left are: 4
Total coupouns left are: 3
Total coupouns left are: 2
Total coupouns left are: 1
Total coupouns left are: 0
No counpouns left


In [221]:
while False:
    print('Hi')
print('H')

H


In [222]:
sales = [34545,55555,44344,33333]
profit = [4343,4445,4445,4444]

In [228]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(round(profit[i]/sales[i],2))
print(profitratio)

[0.13, 0.08, 0.1, 0.13]


In [235]:
marks = 81
if marks<40:
    print('Failed')
elif marks>=40 or marks<=60:
    print('Avg')
elif marks>60 and marks<=80:
    print('Good')
else:
    print('Excellent')

Avg


# Ternary Operator

In [239]:
a=30
b=20
abc = a if a <b else b
print(abc)

20


In [ ]:
sales = [34545,55555,44344,33333]
profit = [4343,4445,4445,4444]

In [ ]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(round(profit[i]/sales[i],2))
print(profitratio)

In [241]:
import numpy as np

In [243]:
sales_array = np.array(sales)

In [244]:
sales_array

array([34545, 55555, 44344, 33333])

In [245]:
profit_array = np.array(profit)

In [246]:
profit_array

array([4343, 4445, 4445, 4444])

In [247]:
profit_array/sales_array

array([0.12572008, 0.0800108 , 0.10023904, 0.13332133])

In [248]:
np.array([1,2,3,4,'R'])

array(['1', '2', '3', '4', 'R'], dtype='<U11')

In [250]:
mylist = [1,2,3,4,5]

In [251]:
mylist

[1, 2, 3, 4, 5]

In [253]:
myarray = np.array(mylist)

In [255]:
mylist*3

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [254]:
myarray*3

array([ 3,  6,  9, 12, 15])

In [277]:
mylist = [1,2,3,4,True]

In [278]:
np.array(mylist)

array([1, 2, 3, 4, 1])

In [258]:
mylist = [1,2,3,4,5,6]

In [259]:
myarray = np.array(mylist)

In [265]:
slicearray = myarray[0:4]

In [266]:
slicearray

array([1, 2, 3, 4])

In [263]:
slicelist = mylist[0:4]

In [268]:
slicelist[0]=100

In [269]:
slicelist

[100, 2, 3, 4]

In [270]:
mylist

[1, 2, 3, 4, 5, 6]

In [271]:
slicearray[0]=100

In [272]:
slicearray

array([100,   2,   3,   4])

In [273]:
myarray

array([100,   2,   3,   4,   5,   6])

In [281]:
sales_us = [212,222,323,222]
sales_eu = [343,444,443,333]
sales_in = [443,333,232,222]

In [282]:
sales_array = np.array([sales_us,sales_eu,sales_in])

In [283]:
sales_array

array([[212, 222, 323, 222],
       [343, 444, 443, 333],
       [443, 333, 232, 222]])

In [284]:
profit_us=[32,33,23,22]
profit_eu=[44,44,44,33]
profit_in=[23,44,55,45]

In [285]:
profit_matrix = np.array([profit_us,profit_eu,profit_in])

In [286]:
profit_matrix

array([[32, 33, 23, 22],
       [44, 44, 44, 33],
       [23, 44, 55, 45]])

In [290]:
profit_matrix/sales_array

array([[0.1509434 , 0.14864865, 0.07120743, 0.0990991 ],
       [0.12827988, 0.0990991 , 0.0993228 , 0.0990991 ],
       [0.05191874, 0.13213213, 0.23706897, 0.2027027 ]])

In [292]:
sales_array[2,2]

232

In [294]:
sales_array[2][2]

232

In [296]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [299]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [301]:
np.reshape(np.arange(0,20),(5,4),'F')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [303]:
a=np.reshape(np.arange(0,20),(5,4),'F')

In [308]:
np.reshape(a,(1,20),'F')

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19]])

In [302]:
sales_array

array([[212, 222, 323, 222],
       [343, 444, 443, 333],
       [443, 333, 232, 222]])

In [312]:
rdict = {'US':0, 'EU':1,'IN':2}
qdict = {'Q1':0,'Q2':1,'Q3':2, 'Q4':3}

In [325]:
sales_array[rdict['EU']][qdict['Q3']]

443

In [323]:
sales_array[:,qdict['Q2']:qdict['Q4']]

array([[222, 323],
       [444, 443],
       [333, 232]])