In [1]:
import os
os.chdir('D:\\D\\Cognitior\\Deep Learning\\ANN\\')

In [4]:
os.getcwd()

'D:\\D\\Cognitior\\Deep Learning\\ANN'

In [3]:
import pandas as pd 
import numpy as np
import tensorflow as tf
import keras

Using TensorFlow backend.


In [5]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [18]:
dataset

RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0          2       0.00              1          1               1   
1          1   83807.86              1          0               1   
2          8  159660.80              3          1               0   
3          1       0.00              2          0               0   
4          2  125510.82              1          1               1   
...      ...        ...            ...        ...             ...   
9995       5       0.00              2          1               0   
9996      10   57369.61              1          1               1   
9997       7       0.00              1          0               1   
9998       3   75075.31              2          1               0   
9999       4  130142.79              1          1               0   

      EstimatedSalary  Exited  
0           101348.88       1  
1           112542.58       0  
2           113931.57       1  
3            93826.63       0  
4            79084.10       0  
...               ...     ...  
9995         96270.64       0  
9996        101699.77       0  
9997         42085.58       1  
9998         92888.52       1  
9999         38190.78       0  

[10000 rows x 14 columns]

In [8]:
len(dataset.columns)

14

In [16]:
lis1 = [1,2,3,4,5]

In [17]:
lis1[0:3]

[1, 2, 3]

In [12]:
x = dataset.iloc[:,3:13].values

In [13]:
y = dataset.iloc[:,13].values

In [14]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [15]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [23]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])
x[:,2] = labelencoder_x_1.fit_transform(x[:,2])

In [24]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [25]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [27]:
pd.DataFrame(x)

0    1    2      3    4     5     6          7    8    9   10  \
0     1.0  0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     0.0  0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     0.0  0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
...   ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9995  1.0  0.0  0.0  771.0  1.0  39.0   5.0       0.00  2.0  1.0  0.0   
9996  1.0  0.0  0.0  516.0  1.0  35.0  10.0   57369.61  1.0  1.0  1.0   
9997  1.0  0.0  0.0  709.0  0.0  36.0   7.0       0.00  1.0  0.0  1.0   
9998  0.0  1.0  0.0  772.0  1.0  42.0   3.0   75075.31  2.0  1.0  0.0   
9999  1.0  0.0  0.0  792.0  0.0  28.0   4.0  130142.79  1.0  1.0  0.0   

             11  
0     101348.88  
1     112542.58  
2     113931.57  
3      93826.63  
4      79084.10  
...         ...  
9995   96270.64  
9996  101699.77  
9997   42085.58  
9998   92888.52  
9999   38190.78  

[10000 rows x 12 columns]

In [50]:
x=x[:,1:]

In [52]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0    -0.578736 -0.573809 -0.326221 -1.095988  0.293517 -1.041760 -1.225848   
1    -0.578736  1.742740 -0.440036 -1.095988  0.198164 -1.387538  0.117350   
2    -0.578736 -0.573809 -1.536794 -1.095988  0.293517  1.032908  1.333053   
3    -0.578736 -0.573809  0.501521 -1.095988  0.007457 -1.387538 -1.225848   
4    -0.578736  1.742740  2.063884 -1.095988  0.388871 -1.041760  0.785728   
...        ...       ...       ...       ...       ...       ...       ...   
9995 -0.578736 -0.573809  1.246488  0.912419  0.007457 -0.004426 -1.225848   
9996 -0.578736 -0.573809 -1.391939  0.912419 -0.373958  1.724464 -0.306379   
9997 -0.578736 -0.573809  0.604988 -1.095988 -0.278604  0.687130 -1.225848   
9998  1.727904 -0.573809  1.256835  0.912419  0.293517 -0.695982 -0.022608   
9999 -0.578736 -0.573809  1.463771 -1.095988 -1.041433 -0.350204  0.859965   

             7         8         9        10  
0    -0.911583  0.646092  0.970243  0.021886  
1    -0.911583 -1.547768  0.970243  0.216534  
2     2.527057  0.646092 -1.030670  0.240687  
3     0.807737 -1.547768 -1.030670 -0.108918  
4    -0.911583  0.646092  0.970243 -0.365276  
...        ...       ...       ...       ...  
9995  0.807737  0.646092 -1.030670 -0.066419  
9996 -0.911583  0.646092  0.970243  0.027988  
9997 -0.911583 -1.547768  0.970243 -1.008643  
9998  0.807737  0.646092 -1.030670 -0.125231  
9999 -0.911583  0.646092 -1.030670 -1.076370  

[10000 rows x 11 columns]

In [28]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [29]:
pd.DataFrame(x)

0         1         2         3         4         5         6  \
0     0.997204 -0.578736 -0.573809 -0.326221 -1.095988  0.293517 -1.041760   
1    -1.002804 -0.578736  1.742740 -0.440036 -1.095988  0.198164 -1.387538   
2     0.997204 -0.578736 -0.573809 -1.536794 -1.095988  0.293517  1.032908   
3     0.997204 -0.578736 -0.573809  0.501521 -1.095988  0.007457 -1.387538   
4    -1.002804 -0.578736  1.742740  2.063884 -1.095988  0.388871 -1.041760   
...        ...       ...       ...       ...       ...       ...       ...   
9995  0.997204 -0.578736 -0.573809  1.246488  0.912419  0.007457 -0.004426   
9996  0.997204 -0.578736 -0.573809 -1.391939  0.912419 -0.373958  1.724464   
9997  0.997204 -0.578736 -0.573809  0.604988 -1.095988 -0.278604  0.687130   
9998 -1.002804  1.727904 -0.573809  1.256835  0.912419  0.293517 -0.695982   
9999  0.997204 -0.578736 -0.573809  1.463771 -1.095988 -1.041433 -0.350204   

             7         8         9        10        11  
0    -1.225848 -0.911583  0.646092  0.970243  0.021886  
1     0.117350 -0.911583 -1.547768  0.970243  0.216534  
2     1.333053  2.527057  0.646092 -1.030670  0.240687  
3    -1.225848  0.807737 -1.547768 -1.030670 -0.108918  
4     0.785728 -0.911583  0.646092  0.970243 -0.365276  
...        ...       ...       ...       ...       ...  
9995 -1.225848  0.807737  0.646092 -1.030670 -0.066419  
9996 -0.306379 -0.911583  0.646092  0.970243  0.027988  
9997 -1.225848 -0.911583 -1.547768  0.970243 -1.008643  
9998 -0.022608  0.807737  0.646092 -1.030670 -0.125231  
9999  0.859965 -0.911583  0.646092 -1.030670 -1.076370  

[10000 rows x 12 columns]

In [53]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [31]:
len(x_test)

2000

In [32]:
len(x_train)

8000

In [54]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [55]:
y_pred  = logmodel.predict(x_test)

In [56]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[1526,   69],
       [ 309,   96]], dtype=int64)

In [57]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.811

In [58]:
from keras.models import Sequential
from keras.layers import Dense

In [59]:
classifier = Sequential()

In [60]:
classifier.add(Dense(units=6, 
                     kernel_initializer='uniform', 
                     activation='relu',input_dim = 11 ))

In [61]:
classifier.add(Dense(units=6, 
                     kernel_initializer='uniform',
                    activation='relu'))

In [62]:
classifier.add(Dense(units=1, 
                     kernel_initializer='uniform',
                    activation='sigmoid'))

In [63]:
classifier.compile(optimizer='adam',
                   loss='binary_crossentropy', 
                   metrics=['accuracy'])

In [64]:
pd.DataFrame(x_train)

0         1         2         3         4         5         6  \
0    -0.578736  1.742740  0.170424 -1.095988 -0.469311 -0.004426 -1.225848   
1     1.727904 -0.573809 -2.312802  0.912419  0.293517 -1.387538 -0.012892   
2    -0.578736 -0.573809 -1.195351 -1.095988 -0.946079 -1.041760  0.575076   
3    -0.578736  1.742740  0.035916  0.912419  0.102810 -0.004426  0.467955   
4    -0.578736  1.742740  2.063884 -1.095988  1.723821  1.032908  0.806010   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.727904 -0.573809 -0.584891 -1.095988 -0.660018 -0.350204  0.698607   
7996 -0.578736  1.742740  1.484464 -1.095988 -1.613554 -0.350204  0.608299   
7997 -0.578736 -0.573809  0.905045  0.912419 -0.373958 -0.004426  1.358909   
7998 -0.578736  1.742740 -0.626278 -1.095988 -0.087897  1.378686 -1.225848   
7999  1.727904 -0.573809 -0.284834 -1.095988  0.865639 -1.387538  0.506303   

             7         8         9        10  
0     0.807737  0.646092 -1.030670  1.108382  
1    -0.911583  0.646092  0.970243 -0.747592  
2    -0.911583  0.646092 -1.030670  1.487464  
3    -0.911583  0.646092 -1.030670  1.278558  
4     0.807737  0.646092  0.970243  0.560069  
...        ...       ...       ...       ...  
7995  0.807737  0.646092  0.970243  1.093273  
7996 -0.911583  0.646092  0.970243  0.133249  
7997  0.807737  0.646092 -1.030670  1.414415  
7998  0.807737  0.646092  0.970243  0.846147  
7999 -0.911583  0.646092 -1.030670  0.326305  

[8000 rows x 11 columns]

In [65]:
classifier.fit(x_train, y_train, batch_size=10, epochs=100)

Epoch 1/100
8000/8000 [==============================] - 2s 211us/step - loss: 0.4823 - accuracy: 0.7959
Epoch 2/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4262 - accuracy: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 144us/step - loss: 0.4204 - accuracy: 0.8073
Epoch 4/100
8000/8000 [==============================] - 1s 140us/step - loss: 0.4170 - accuracy: 0.8246
Epoch 5/100
8000/8000 [==============================] - 1s 150us/step - loss: 0.4147 - accuracy: 0.8292
Epoch 6/100
8000/8000 [==============================] - 1s 148us/step - loss: 0.4129 - accuracy: 0.8325
Epoch 7/100
8000/8000 [==============================] - 1s 149us/step - loss: 0.4122 - accuracy: 0.8314
Epoch 8/100
8000/8000 [==============================] - 1s 146us/step - loss: 0.4108 - accuracy: 0.8317
Epoch 9/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4100 - accuracy: 0.8325
Epoch 10/100
8000/8000 [==============================]

In [66]:
y_pred = classifier.predict(x_test)

In [69]:
y_pred = (y_pred>0.5)

In [70]:
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [71]:
confusion_matrix(y_test, y_pred)

array([[1543,   52],
       [ 259,  146]], dtype=int64)

In [72]:
accuracy_score(y_test,y_pred)

0.8445

In [88]:
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import cross_val_score

In [89]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                        activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                        activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform',
                        activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',
                      metrics=['accuracy'])
    return classifier


In [92]:
classifier = KerasClassifier(build_fn=build_classifier,
                            batch_size=50, epochs=50)
accuracies = cross_val_score(estimator=classifier, X=x_train, 
                            y=y_train, cv=10)

Epoch 1/50
7200/7200 [==============================] - 1s 95us/step - loss: 0.6401 - accuracy: 0.7940
Epoch 2/50
7200/7200 [==============================] - 0s 34us/step - loss: 0.4720 - accuracy: 0.7971
Epoch 3/50
7200/7200 [==============================] - 0s 33us/step - loss: 0.4372 - accuracy: 0.7971
Epoch 4/50
7200/7200 [==============================] - 0s 33us/step - loss: 0.4323 - accuracy: 0.7971
Epoch 5/50
7200/7200 [==============================] - 0s 32us/step - loss: 0.4303 - accuracy: 0.7971
Epoch 6/50
7200/7200 [==============================] - 0s 32us/step - loss: 0.4285 - accuracy: 0.7971
Epoch 7/50
7200/7200 [==============================] - 0s 32us/step - loss: 0.4271 - accuracy: 0.7971
Epoch 8/50
7200/7200 [==============================] - 0s 33us/step - loss: 0.4257 - accuracy: 0.7971
Epoch 9/50
7200/7200 [==============================] - 0s 28us/step - loss: 0.4241 - accuracy: 0.7971
Epoch 10/50
7200/7200 [==============================] - 0s 29us/step - l

In [95]:
accuracies.mean()

0.8378750026226044

In [96]:
accuracies.std()

0.010869257542623724

In [ ]:
#Improving the ANN

In [97]:
from keras.wrappers.scikit_learn import KerasClassifier
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import GridSearchCV


In [105]:
def build_classifier():
    classifier=Sequential()
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                        activation='relu', input_dim=11))
    classifier.add(Dense(units=6, kernel_initializer='uniform',
                        activation='relu'))
    classifier.add(Dense(units=1, kernel_initializer='uniform',
                        activation='sigmoid'))
    classifier.compile(optimizer='adam',loss='binary_crossentropy',
                      metrics=['accuracy'])
    return classifier

In [116]:
classifier = KerasClassifier(build_fn=build_classifier)
parameters = {'batch_size': [50,75],
             'epochs':[50,70]
             #'optimizer':['adam','rmsprop']
             } 
grid_search = GridSearchCV(estimator=classifier, 
                          param_grid=parameters,
                          scoring='accuracy',
                          cv=5)
grid_search=grid_search.fit(x_train,y_train)
best_parameters = grid_search.best_params_
best_accuracy = grid_search.best_score_

Epoch 1/50
6400/6400 [==============================] - 1s 117us/step - loss: 0.6629 - accuracy: 0.7959
Epoch 2/50
6400/6400 [==============================] - 0s 39us/step - loss: 0.5233 - accuracy: 0.7980
Epoch 3/50
6400/6400 [==============================] - 0s 34us/step - loss: 0.4420 - accuracy: 0.7980
Epoch 4/50
6400/6400 [==============================] - 0s 36us/step - loss: 0.4256 - accuracy: 0.7980
Epoch 5/50
6400/6400 [==============================] - 0s 36us/step - loss: 0.4170 - accuracy: 0.8095
Epoch 6/50
6400/6400 [==============================] - 0s 36us/step - loss: 0.4099 - accuracy: 0.8245
Epoch 7/50
6400/6400 [==============================] - 0s 43us/step - loss: 0.4040 - accuracy: 0.8270
Epoch 8/50
6400/6400 [==============================] - 0s 43us/step - loss: 0.3989 - accuracy: 0.8283
Epoch 9/50
6400/6400 [==============================] - 0s 40us/step - loss: 0.3948 - accuracy: 0.8288
Epoch 10/50
6400/6400 [==============================] - 0s 37us/step - 

In [117]:
best_accuracy

0.840875

In [118]:
best_parameters

{'batch_size': 50, 'epochs': 50}