In [ ]:
#Today's 
#Cross validation 
#Model Saving
#Smote 
#Recommendation Engine

In [ ]:
#Reinforcement Learning
#Dimensionality Reduction Maths 

In [1]:
import pandas as pd
import numpy as np
import os
os.chdir(r'C:\Users\Admin\Desktop\CA')

In [2]:
from sklearn import linear_model

In [3]:
df = pd.read_excel('Houseprice.xlsx')

In [4]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
model = linear_model.LinearRegression()
model.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
model.coef_

array([135.78767123])

In [7]:
model.intercept_

180616.43835616432

In [8]:
model.predict([[5000]])

array([859554.79452055])

In [9]:
import pickle

In [10]:
with open('model_pickle', 'wb') as file:
    pickle.dump(model, file)

In [11]:
with open('model_pickle', 'rb') as file:
    mp = pickle.load(file)

In [12]:
mp.coef_

array([135.78767123])

In [13]:
mp.intercept_

180616.43835616432

In [14]:
mp.predict([[5000]])

array([859554.79452055])