In [ ]:
#Questions

In [1]:
#Dictionaries
mycust = {'cust_name':'Rahul', 'age':33, 'Region':'APAC'}

In [2]:
mycust

{'cust_name': 'Rahul', 'age': 33, 'Region': 'APAC'}

In [3]:
mycust['cust_name']

'Rahul'

In [4]:
mycust['product']='Python'

In [6]:
len(mycust)

4

In [7]:
mystuds = {'s_id':[1,2,3,4,5],
          's_name':['A','B','C','D','E'],
          'course':['Py','Tab','R','PBI','Py']}

In [8]:
mystuds

{'s_id': [1, 2, 3, 4, 5],
 's_name': ['A', 'B', 'C', 'D', 'E'],
 'course': ['Py', 'Tab', 'R', 'PBI', 'Py']}

In [11]:
mystuds['s_id'][0]=10

In [12]:
mystuds

{'s_id': [10, 2, 3, 4, 5],
 's_name': ['A', 'B', 'C', 'D', 'E'],
 'course': ['Py', 'Tab', 'R', 'PBI', 'Py']}

In [13]:
import pandas as pd

In [14]:
pd.DataFrame(mystuds)

s_id s_name course
0    10      A     Py
1     2      B    Tab
2     3      C      R
3     4      D    PBI
4     5      E     Py

In [18]:
mycust['Continent']=mycust.pop('Region')

In [19]:
mycust

{'cust_name': 'Rahul', 'age': 33, 'product': 'Python', 'Continent': 'APAC'}

In [21]:
mystuds.keys()

dict_keys(['s_id', 's_name', 'course'])

In [22]:
mystuds.values()

dict_values([[10, 2, 3, 4, 5], ['A', 'B', 'C', 'D', 'E'], ['Py', 'Tab', 'R', 'PBI', 'Py']])

In [23]:
mynewdict = mystuds.fromkeys({'s_id','course'},'NA')

In [24]:
mynewdict

{'course': 'NA', 's_id': 'NA'}

In [28]:
dict1 = {1:1,3:5}
dict2 = {4:2,3:3}

In [29]:
dict2

{3: 3}

In [26]:
dict1.update(dict2)

In [27]:
dict1

{1: 1, 3: 3, 4: 2}

In [30]:
#Set
myset = {1,1,2,3,4,5,5,6,6,6,77,7,7,9}

In [31]:
myset

{1, 2, 3, 4, 5, 6, 7, 9, 77}

In [33]:
myset[0]=10

TypeError: 'set' object does not support item assignment

In [34]:
mylist=[1,1,2,3,4,4]

In [35]:
set(mylist)

{1, 2, 3, 4}

In [40]:
myset.add([10,20,30])

TypeError: unhashable type: 'list'

In [41]:
myset.update([10,20,30,40])

In [42]:
myset

{1, 2, 3, 4, 5, 6, 7, 9, 10, 20, 30, 40, 77}

In [45]:
myset.remove(77)

KeyError: 77

In [54]:
myset.discard(77)

In [48]:
myset

{1, 2, 3, 4, 5, 6, 7, 9, 10, 20, 30, 40}

In [57]:
myset.pop()

2

In [58]:
myset

{3, 4, 5, 6, 7, 9, 10, 20, 30, 40}

In [59]:
myset1={1,2,3}
myset2 = {3,4,5}

In [60]:
myset1.union(myset2)

{1, 2, 3, 4, 5}

In [61]:
myset1.intersection(myset2)

{3}

In [ ]:
#While 
while condition {
    statement1
    statement2
}
statement3

In [ ]:
while condition:
    statement1
    statement2
statement3

In [64]:
coupouns = 5
utilized = 0
while utilized<5:
    print('Total coupouns left are ' + str(coupouns-utilized))
    utilized=utilized+1
print('No counpouns left')

Total coupouns left are 5
Total coupouns left are 4
Total coupouns left are 3
Total coupouns left are 2
Total coupouns left are 1
No counpouns left


In [67]:
#if else
marks = 65
if marks<40:
    print('Fail')
elif marks>=40 and marks<=60:
    print('Avg')
else:
    print('Ex')

Ex


In [68]:
#Arrays
import numpy as np

In [69]:
sales = [2323,4443,4322,3223]

profit = [343,455,443,223]

In [70]:
profitratio = []
for i in range(0,len(sales)):
    profitratio.append(profit[i]/sales[i])
profitratio

[0.14765389582436506,
 0.10240828269187487,
 0.1024988431281814,
 0.06919019547005895]

In [76]:
sales_array = np.array([2323,4443,4322,3223])

profit_array = np.array([343,455,443])

In [74]:
type(profit_array)

numpy.ndarray

In [73]:
sales_array

array([2323, 4443, 4322, 3223])

In [77]:
profit_array/sales_array

ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [79]:
sales*3

[2323, 4443, 4322, 3223, 2323, 4443, 4322, 3223, 2323, 4443, 4322, 3223]

In [80]:
sales_array*3

array([ 6969, 13329, 12966,  9669])

In [83]:
sales_slice =sales_array[0:2]

In [100]:
sales_array

array([ 200, 4443, 4322, 3223])

In [102]:
sales_slice

array([ 200, 4443])

In [99]:
sales_array[0]=200

In [94]:
s_c[0]=0

In [101]:
s_c

array([   0, 4443, 4322, 3223])

In [113]:
mylist = [1,2,3,False]

In [104]:
mylist

[1, 2, 3, 'R', True]

In [109]:
type(mylist[4])

bool

In [114]:
np.array(mylist)

array([1, 2, 3, 0])

In [116]:
a=np.arange(0,20)

In [117]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [121]:
np.reshape(a,(4,5),'F')

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [122]:
sales_uk = [1232,3432,3223,4455]
sales_us = [4343,2234,2345,4332]
sales_eu = [3434,4465,4323,4456]

In [124]:
sales_matrix=np.array([sales_uk,sales_us,sales_eu])

In [125]:
sales_matrix

array([[1232, 3432, 3223, 4455],
       [4343, 2234, 2345, 4332],
       [3434, 4465, 4323, 4456]])

In [126]:
profit_uk = [323,332,223,343]
profit_us=[454,222,324,333]
profit_eu=[234,443,322,343]

In [128]:
profit_matrix=np.array([profit_uk,profit_us,profit_eu])

In [129]:
profit_matrix

array([[323, 332, 223, 343],
       [454, 222, 324, 333],
       [234, 443, 322, 343]])

In [130]:
sales_matrix

array([[1232, 3432, 3223, 4455],
       [4343, 2234, 2345, 4332],
       [3434, 4465, 4323, 4456]])

In [131]:
profit_matrix/sales_matrix

array([[0.26217532, 0.0967366 , 0.0691902 , 0.07699214],
       [0.10453603, 0.09937332, 0.13816631, 0.07686981],
       [0.06814211, 0.09921613, 0.07448531, 0.07697487]])

In [134]:
sales_matrix[2][2]

4323

In [135]:
sales_matrix

array([[1232, 3432, 3223, 4455],
       [4343, 2234, 2345, 4332],
       [3434, 4465, 4323, 4456]])

In [136]:
rdict = {'UK':0, 'US':1,'EU':2}
qdict={'Q1':0,'Q2':1,'Q3':2,'Q4':3}

In [137]:
sales_matrix[rdict['UK']][qdict['Q3']]

3223

In [ ]:
#DataFrames

In [138]:
stu_dic = {'s_id':[1,2,3,4,5],
          's_name':['A','B','C','D','E'],
          'Region':['N','S','S','E','W']}

sales_dic = {'stu_id':[1,2,3,4,6],
            'Course':['Py','R','Tab','R','Orc'],
            'Sales':[212,332,223,222,334]}

In [139]:
stu_details = pd.DataFrame(stu_dic)

In [140]:
sales_details = pd.DataFrame(sales_dic)

In [141]:
stu_details

s_id s_name Region
0     1      A      N
1     2      B      S
2     3      C      S
3     4      D      E
4     5      E      W

In [142]:
sales_details

stu_id Course  Sales
0       1     Py    212
1       2      R    332
2       3    Tab    223
3       4      R    222
4       6    Orc    334

In [148]:
pd.merge(stu_details,sales_details,left_on='s_id',right_on='stu_id',how='outer')

s_id s_name Region  stu_id Course  Sales
0   1.0      A      N     1.0     Py  212.0
1   2.0      B      S     2.0      R  332.0
2   3.0      C      S     3.0    Tab  223.0
3   4.0      D      E     4.0      R  222.0
4   5.0      E      W     NaN    NaN    NaN
5   NaN    NaN    NaN     6.0    Orc  334.0

In [149]:
pd.merge(stu_details,sales_details,left_on='s_id',right_on='stu_id',how='inner')

s_id s_name Region  stu_id Course  Sales
0     1      A      N       1     Py    212
1     2      B      S       2      R    332
2     3      C      S       3    Tab    223
3     4      D      E       4      R    222

In [150]:
pd.merge(stu_details,sales_details,left_on='s_id',right_on='stu_id',how='left')

s_id s_name Region  stu_id Course  Sales
0     1      A      N     1.0     Py  212.0
1     2      B      S     2.0      R  332.0
2     3      C      S     3.0    Tab  223.0
3     4      D      E     4.0      R  222.0
4     5      E      W     NaN    NaN    NaN

In [151]:
pd.merge(stu_details,sales_details,left_on='s_id',right_on='stu_id',how='right')

s_id s_name Region  stu_id Course  Sales
0   1.0      A      N       1     Py    212
1   2.0      B      S       2      R    332
2   3.0      C      S       3    Tab    223
3   4.0      D      E       4      R    222
4   NaN    NaN    NaN       6    Orc    334

In [154]:
pd.read_csv('C:\\Users\\Admin\\Desktop\\tips.csv')

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [153]:
import os
os.getcwd()

'C:\\Users\\Admin'

In [155]:
os.chdir('C:\\Users\\Admin\\Desktop\\')

In [157]:
tips=pd.read_csv('tips.csv')

In [159]:
type(tips)

pandas.core.frame.DataFrame

In [160]:
len(tips)

244

In [162]:
len(tips.columns)

7

In [165]:
tips.head(1)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2

In [168]:
tips.tail(7)

total_bill   tip     sex smoker   day    time  size
237       32.83  1.17    Male    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [169]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null object
smoker        244 non-null object
day           244 non-null object
time          244 non-null object
size          244 non-null int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [170]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [171]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [172]:
tips[['total_bill','sex','smoker','time']]

total_bill     sex smoker    time
0         16.99  Female     No  Dinner
1         10.34    Male     No  Dinner
2         21.01    Male     No  Dinner
3         23.68    Male     No  Dinner
4         24.59  Female     No  Dinner
..          ...     ...    ...     ...
239       29.03    Male     No  Dinner
240       27.18  Female    Yes  Dinner
241       22.67    Male    Yes  Dinner
242       17.82    Male     No  Dinner
243       18.78  Female     No  Dinner

[244 rows x 4 columns]

In [174]:
tips[tips['time']=='Dinner']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [178]:
len(tips[(tips['time']=='Dinner') & (tips['sex']=='Female')])

52

In [180]:
tips[(tips['size']>5) | (tips['total_bill']>45)]

total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
143       27.05   5.00  Female     No  Thur   Lunch     6
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4

In [185]:
tips.groupby(['smoker','sex']).agg({'tip':np.mean})

tip
smoker sex             
No     Female  2.773519
       Male    3.113402
Yes    Female  2.931515
       Male    3.051167

In [182]:
tips.groupby(['smoker','sex']).size()

smoker  sex   
No      Female    54
        Male      97
Yes     Female    33
        Male      60
dtype: int64

In [187]:
df=tips[(tips['size']>5) | (tips['total_bill']>45)]

In [189]:
df.to_csv('df.csv')