In [ ]:
#Scaler [1] 
#Vector [1,2,3]
#Matrix [1,2,3
#        3,4,5
#        5,6,7]
#Tensors - Collection of matries

In [1]:
import numpy as np

In [2]:
my_data=np.arange(0,30)

In [3]:
my_data

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [4]:
type(my_data)

numpy.ndarray

In [8]:
matrix_1=np.reshape(my_data,(6,5),'F')

In [9]:
matrix_1

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [10]:
type(matrix_1)

numpy.ndarray

In [11]:
matrix_1[4,3]

22

In [12]:
North=[2345,5545,4456,4445,4444,7677]
south=[4445,5565,4454,5677,5556,4443]
east=[4454,6678,7776,6767,8887,9999]
west=[5565,6656,3323,3343,4454,5555]

In [13]:
sales_matrix=np.array([North,south,east,west])

In [14]:
sales_matrix

array([[2345, 5545, 4456, 4445, 4444, 7677],
       [4445, 5565, 4454, 5677, 5556, 4443],
       [4454, 6678, 7776, 6767, 8887, 9999],
       [5565, 6656, 3323, 3343, 4454, 5555]])

In [15]:
sales_matrix.T

array([[2345, 4445, 4454, 5565],
       [5545, 5565, 6678, 6656],
       [4456, 4454, 7776, 3323],
       [4445, 5677, 6767, 3343],
       [4444, 5556, 8887, 4454],
       [7677, 4443, 9999, 5555]])