In [1]:
north_sales=[3324,3345,4454,3221]
east_sales=[4454,6656,7787,4443]
west_sales=[4443,5554,5555,3322]

In [2]:
north_profit=[334,444,222,343]
east_profit=[444,545,444,332]
west_profit=[556,665,333,222]

In [3]:
import numpy as np
sales_matrix=np.array([north_sales,east_sales,west_sales])

In [4]:
sales_matrix

array([[3324, 3345, 4454, 3221],
       [4454, 6656, 7787, 4443],
       [4443, 5554, 5555, 3322]])

In [5]:
profit_matrix=np.array([north_profit,east_profit,west_profit])

In [6]:
profit_matrix

array([[334, 444, 222, 343],
       [444, 545, 444, 332],
       [556, 665, 333, 222]])

In [7]:
profit_matrix/sales_matrix

array([[0.10048135, 0.13273543, 0.04984284, 0.10648867],
       [0.09968568, 0.08188101, 0.05701811, 0.07472429],
       [0.12514067, 0.11973353, 0.05994599, 0.06682721]])

In [8]:
profit_matrix[0,3]

343

In [9]:
quarter=['Q1','Q2','Q3','Q4']
region=['North','East','West']

In [10]:
quarter_dict = {'Q1':0,'Q2':1,'Q3':2,'Q4':3}
region_dict={'North':0,'East':1,'West':2}

In [12]:
profit_matrix[region_dict['West'],quarter_dict['Q1']]

556