In [1]:
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
A = np.array([[8,-6,2],[-6,7,-4],[2,-4,3]])
A

array([[ 8, -6,  2],
       [-6,  7, -4],
       [ 2, -4,  3]])

In [4]:
np.linalg.eig(A)

(array([1.50000000e+01, 3.00000000e+00, 8.95419849e-16]),
 array([[-0.66666667,  0.66666667,  0.33333333],
        [ 0.66666667,  0.33333333,  0.66666667],
        [-0.33333333, -0.66666667,  0.66666667]]))

In [5]:
w,v = np.linalg.eig(A)

In [6]:
w

array([1.50000000e+01, 3.00000000e+00, 8.95419849e-16])

In [7]:
for i in w:
    print(i)

15.000000000000007
3.000000000000003
8.954198494978331e-16


In [8]:
v

array([[-0.66666667,  0.66666667,  0.33333333],
       [ 0.66666667,  0.33333333,  0.66666667],
       [-0.33333333, -0.66666667,  0.66666667]])

In [9]:
for i in v:
    print(i)

[-0.66666667  0.66666667  0.33333333]
[0.66666667 0.33333333 0.66666667]
[-0.33333333 -0.66666667  0.66666667]


In [10]:
from sklearn.decomposition import PCA

In [11]:
pca = PCA(n_components = 3)

In [12]:
pca.fit(A)

PCA(copy=True, iterated_power='auto', n_components=3, random_state=None,
  svd_solver='auto', tol=0.0, whiten=False)

In [13]:
print(pca.components_)

[[-0.6613039   0.66931595 -0.338664  ]
 [-0.67198663 -0.32798127  0.66397459]
 [ 0.33333333  0.66666667  0.66666667]]


In [10]:
import os
os.chdir(r'D:\D\Edureka\Edureka - 24 June - Python\Class 16')

In [11]:
import pandas as pd

In [12]:
dataset = pd.read_csv('Bank-data.csv')

In [13]:
dataset

Index  interest_rate  credit  Gender  previous  duration Churn
0        0          1.334       0       1         0       117    no
1        1          0.767       0       0         1       274   yes
2        2          4.858       0       1         0       167    no
3        3          4.120       0       0         0       686   yes
4        4          4.856       0       1         0       159    no
..     ...            ...     ...     ...       ...       ...   ...
513    513          1.334       0       1         0       204    no
514    514          0.861       0       0         1       806   yes
515    515          0.879       0       0         0       290    no
516    516          0.877       0       0         1       473   yes
517    517          4.965       0       0         0       142    no

[518 rows x 7 columns]

In [14]:
dataset['Churn'] = dataset['Churn'].astype('category')
dataset['Churn'] = dataset['Churn'].cat.codes

In [15]:
dataset

Index  interest_rate  credit  Gender  previous  duration  Churn
0        0          1.334       0       1         0       117      0
1        1          0.767       0       0         1       274      1
2        2          4.858       0       1         0       167      0
3        3          4.120       0       0         0       686      1
4        4          4.856       0       1         0       159      0
..     ...            ...     ...     ...       ...       ...    ...
513    513          1.334       0       1         0       204      0
514    514          0.861       0       0         1       806      1
515    515          0.879       0       0         0       290      0
516    516          0.877       0       0         1       473      1
517    517          4.965       0       0         0       142      0

[518 rows x 7 columns]

In [16]:
x = dataset.iloc[:,1:6].values

In [17]:
y = dataset.iloc[:,6].values

In [18]:
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [20]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [21]:
y_pred = logmodel.predict(x_test)

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred)

array([[45,  8],
       [ 5, 46]], dtype=int64)

In [23]:
accuracy_score(y_test, y_pred)

0.875

In [24]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [28]:
pd.DataFrame(x_train_n)

0         1         2         3         4
0   -309.074400 -1.915458 -0.216130 -0.315404 -0.080151
1    684.925534 -1.461743  0.747903 -0.136504 -0.010124
2     92.925534 -1.535003  0.760538 -0.145170 -0.021119
3   -165.074309 -2.353067 -0.354201  0.646698 -0.112195
4   -240.074439 -1.682241  0.768823 -0.157569 -0.028841
..          ...       ...       ...       ...       ...
409  269.924809  1.251204 -0.262862 -0.087280 -0.024526
410   40.925664 -2.223060 -0.359758  0.657130 -0.106854
411  -88.074377 -2.079231 -0.358780  0.666582 -0.106933
412 -269.074493 -1.544287 -0.221051 -0.288828 -0.074099
413 -223.074492 -1.542601 -0.221989 -0.288439 -0.073303

[414 rows x 5 columns]

In [31]:
sum(pca.explained_variance_ratio_)

1.0

In [29]:
pd.DataFrame(x_train)

0    1    2    3       4
0    1.048  0.0  0.0  0.0    74.0
1    1.250  0.0  1.0  0.0  1068.0
2    1.327  0.0  1.0  0.0   476.0
3    0.644  0.0  0.0  1.0   218.0
4    1.264  0.0  1.0  0.0   143.0
..     ...  ...  ...  ...     ...
409  4.076  0.0  0.0  0.0   653.0
410  0.722  0.0  0.0  1.0   424.0
411  0.899  0.0  0.0  1.0   295.0
412  1.410  0.0  0.0  0.0   114.0
413  1.400  0.0  0.0  0.0   160.0

[414 rows x 5 columns]

In [49]:
from sklearn.decomposition import PCA
pca = PCA(n_components=None)
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [50]:
pd.DataFrame(x_train_n)

0         1         2         3         4
0   -309.074400 -1.915458 -0.216130 -0.315404 -0.080151
1    684.925534 -1.461743  0.747903 -0.136504 -0.010124
2     92.925534 -1.535003  0.760538 -0.145170 -0.021119
3   -165.074309 -2.353067 -0.354201  0.646698 -0.112195
4   -240.074439 -1.682241  0.768823 -0.157569 -0.028841
..          ...       ...       ...       ...       ...
409  269.924809  1.251204 -0.262862 -0.087280 -0.024526
410   40.925664 -2.223060 -0.359758  0.657130 -0.106854
411  -88.074377 -2.079231 -0.358780  0.666582 -0.106933
412 -269.074493 -1.544287 -0.221051 -0.288828 -0.074099
413 -223.074492 -1.542601 -0.221989 -0.288439 -0.073303

[414 rows x 5 columns]

In [51]:
logmodel = LogisticRegression()
logmodel.fit(x_train_n,y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [52]:
y_pred = logmodel.predict(x_test_n)

In [53]:
confusion_matrix(y_test, y_pred)

array([[28, 25],
       [23, 28]], dtype=int64)

In [54]:
accuracy_score(y_test, y_pred)

0.5384615384615384

In [55]:
os.chdir(r'D:\D\Edureka\Edureka - 24 June - Python\Class 17')

In [57]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [60]:
x=dataset.iloc[:,[2,3]].values

In [61]:
y = dataset.iloc[:,4].values

In [62]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [63]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [64]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [65]:
y_pred = classifier.predict(x_test)

In [66]:
y_pred

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int64)

In [67]:
confusion_matrix(y_test, y_pred)

array([[47,  0],
       [28,  5]], dtype=int64)

In [68]:
accuracy_score(y_test,y_pred)

0.65

In [69]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = x_train, y=y_train, cv=10)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarni

In [71]:
accuracies.mean()

0.675

In [72]:
accuracies.std()

0.028641098093473996

In [74]:
accuracies

array([0.65625, 0.65625, 0.6875 , 0.71875, 0.71875, 0.6875 , 0.625  ,
       0.65625, 0.6875 , 0.65625])