In [1]:
import os
os.chdir(r'D:\D\Edureka\Edureka - 24 June - Python\Class 17')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [6]:
x=dataset.iloc[:,3:13].values

In [8]:
y = dataset.iloc[:,13].values

In [9]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [10]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [11]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [12]:
labelencoder_x = LabelEncoder()
x[:,1] = labelencoder_x.fit_transform(x[:,1])

In [14]:
labelencoder_x = LabelEncoder()
x[:,2] = labelencoder_x.fit_transform(x[:,2])

In [15]:
x

array([[619, 0, 0, ..., 1, 1, 101348.88],
       [608, 2, 0, ..., 0, 1, 112542.58],
       [502, 0, 0, ..., 1, 0, 113931.57],
       ...,
       [709, 0, 0, ..., 0, 1, 42085.58],
       [772, 1, 1, ..., 1, 0, 92888.52],
       [792, 0, 0, ..., 1, 0, 38190.78]], dtype=object)

In [16]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [17]:
pd.DataFrame(x)

0    1    2      3    4     5     6          7    8    9   10  \
0     1.0  0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     0.0  0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     0.0  0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
...   ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9995  1.0  0.0  0.0  771.0  1.0  39.0   5.0       0.00  2.0  1.0  0.0   
9996  1.0  0.0  0.0  516.0  1.0  35.0  10.0   57369.61  1.0  1.0  1.0   
9997  1.0  0.0  0.0  709.0  0.0  36.0   7.0       0.00  1.0  0.0  1.0   
9998  0.0  1.0  0.0  772.0  1.0  42.0   3.0   75075.31  2.0  1.0  0.0   
9999  1.0  0.0  0.0  792.0  0.0  28.0   4.0  130142.79  1.0  1.0  0.0   

             11  
0     101348.88  
1     112542.58  
2     113931.57  
3      93826.63  
4      79084.10  
...         ...  
9995   96270.64  
9996  101699.77  
9997   42085.58  
9998   92888.52  
9999   38190.78  

[10000 rows x 12 columns]

In [18]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [21]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier(n_neighbors=801, p=2)

In [22]:
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=801, p=2,
                     weights='uniform')

In [24]:
y_pred = classifier_knn.predict(x_test)

In [25]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[1583,    0],
       [ 417,    0]], dtype=int64)

In [27]:
from sklearn.svm import SVC
classifier_svm = SVC(kernel='rbf')
classifier_svm.fit(x_train, y_train)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [29]:
y_pred=classifier_svm.predict(x_test)

In [30]:
confusion_matrix(y_test, y_pred)

array([[1583,    0],
       [ 417,    0]], dtype=int64)

In [ ]:
!pip install xgboost

In [31]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=100, n_jobs=1,
              nthread=None, objective='binary:logistic', random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [32]:
y_pred = classifier.predict(x_test)

In [33]:
confusion_matrix(y_test, y_pred)

array([[1536,   47],
       [ 219,  198]], dtype=int64)

In [35]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.867

In [36]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X = x_train, y=y_train, cv=10)
accuracies.mean()

0.8627499999999999

In [37]:
accuracies.std()

0.0055845769759221685

In [38]:
accuracies

array([0.85375, 0.865  , 0.8625 , 0.86375, 0.86375, 0.8525 , 0.86   ,
       0.87   , 0.8675 , 0.86875])

In [39]:
os.chdir(r'C:\Users\Admin\Downloads')

In [41]:
dataset = pd.read_csv('Recommend.csv', names = ['user_id','movie_id','rating','timestamp'])

In [42]:
dataset

user_id  movie_id  rating  timestamp
0          196       242       3  881250949
1          186       302       3  891717742
2           22       377       1  878887116
3          244        51       2  880606923
4          166       346       1  886397596
...        ...       ...     ...        ...
99995      880       476       3  880175444
99996      716       204       5  879795543
99997      276      1090       1  874795795
99998       13       225       2  882399156
99999       12       203       3  879959583

[100000 rows x 4 columns]

In [44]:
n_users = dataset.user_id.unique().shape[0]

In [46]:
n_movies=dataset.movie_id.unique().shape[0]

In [47]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(dataset, test_size=0.25)

In [48]:
train_data_matrix = np.zeros((n_users, n_movies))

In [50]:
pd.DataFrame(train_data_matrix)

0     1     2     3     4     5     6     7     8     9     ...  1672  \
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
939   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
940   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
942   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     1673  1674  1675  1676  1677  1678  1679  1680  1681  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
939   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [51]:
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3]

In [53]:
train_data_matrix[line[1]-1,line[2]-1]

4.0

In [59]:
train_data_matrix[243,707]

4.0

In [54]:
pd.DataFrame(train_data_matrix)

0     1     2     3     4     5     6     7     8     9     ...  1672  \
0     5.0   0.0   0.0   3.0   3.0   5.0   0.0   1.0   5.0   3.0  ...   0.0   
1     4.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   2.0  ...   0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   5.0   0.0  ...   0.0   
939   0.0   0.0   0.0   2.0   0.0   0.0   4.0   5.0   0.0   0.0  ...   0.0   
940   5.0   0.0   0.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   0.0   
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
942   0.0   5.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   0.0   

     1673  1674  1675  1676  1677  1678  1679  1680  1681  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
939   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [56]:
list(train_data.itertuples())

[Pandas(Index=24892, user_id=435, movie_id=174, rating=5, timestamp=884131627),
 Pandas(Index=55764, user_id=244, movie_id=708, rating=4, timestamp=880607231),
 Pandas(Index=30724, user_id=95, movie_id=448, rating=3, timestamp=879197783),
 Pandas(Index=20283, user_id=90, movie_id=617, rating=4, timestamp=891383835),
 Pandas(Index=41604, user_id=495, movie_id=228, rating=5, timestamp=888632738),
 Pandas(Index=84410, user_id=886, movie_id=1067, rating=5, timestamp=876032509),
 Pandas(Index=62623, user_id=867, movie_id=258, rating=3, timestamp=880077751),
 Pandas(Index=30915, user_id=554, movie_id=696, rating=3, timestamp=876232023),
 Pandas(Index=4949, user_id=187, movie_id=70, rating=4, timestamp=879465394),
 Pandas(Index=94985, user_id=145, movie_id=293, rating=4, timestamp=875270276),
 Pandas(Index=59348, user_id=862, movie_id=210, rating=4, timestamp=879304410),
 Pandas(Index=87534, user_id=661, movie_id=496, rating=5, timestamp=876015530),
 Pandas(Index=88385, user_id=588, movie_id=

In [ ]:
for line in test_data.itertuples():
    tes[line[1]-1, line[2]-1] = line[3]

In [60]:
test_data_matrix = np.zeros((n_users, n_movies))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3]

In [61]:
pd.DataFrame(test_data_matrix)

0     1     2     3     4     5     6     7     8     9     ...  1672  \
0     0.0   3.0   4.0   0.0   0.0   0.0   4.0   0.0   0.0   0.0  ...   0.0   
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
4     4.0   3.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
..    ...   ...   ...   ...   ...   ...   ...   ...   ...   ...  ...   ...   
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
939   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   3.0   0.0  ...   0.0   
940   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   
942   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   

     1673  1674  1675  1676  1677  1678  1679  1680  1681  
0     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4     0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
..    ...   ...   ...   ...   ...   ...   ...   ...   ...  
938   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
939   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
940   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
941   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
942   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[943 rows x 1682 columns]

In [63]:
from sklearn.metrics import pairwise_distances

In [64]:
user_similarity = pairwise_distances(train_data_matrix, metric='cosine')
mean_user_rating = train_data_matrix.mean(axis=1)[:,np.newaxis]

In [65]:
rating_diff = (train_data_matrix-mean_user_rating)
user_pred = mean_user_rating + user_similarity.dot(rating_diff)/np.array([np.abs(user_similarity).sum(axis=1)]).T

In [67]:
df_out = pd.DataFrame(user_pred)

In [68]:
df_out.to_csv('output.csv')