In [ ]:
#Nested Loops
#AWS Sagemaker and Google Bert

In [ ]:
while condition:
    statement1
    statement2
statement3

In [ ]:
while condition {
    statement1
    statement2
}
statement3

In [7]:
coupouns = 5
utilized = 0
while utilized<5:
    print('Total coupouns left are '+ str(coupouns-utilized))
    utilized+=1
print('No coupouns left')

Total coupouns left are 5
Total coupouns left are 4
Total coupouns left are 3
Total coupouns left are 2
Total coupouns left are 1
No coupouns left


In [12]:
marks = 90
if marks<40:
    print('Grade 1')
elif marks>40 and marks<70:
    print('Grade 2')
else:
    print('Grade 3')

Grade 3


In [13]:
import numpy as np

In [17]:
type(np.array(sales))

numpy.ndarray

In [14]:
sales = [2343,2334,3434,3433]
profit = [434,554,654,433]

In [16]:
type(sales)

list

In [18]:
sales_array = np.array(sales)

In [19]:
sales_array

array([2343, 2334, 3434, 3433])

In [20]:
profit_array=np.array(profit)

In [22]:
type(profit_array)

numpy.ndarray

In [23]:
profit_array

array([434, 554, 654, 433])

In [24]:
sales_array

array([2343, 2334, 3434, 3433])

In [25]:
profit_array/sales_array

array([0.18523261, 0.23736075, 0.19044846, 0.12612875])

In [27]:
sales*3

[2343, 2334, 3434, 3433, 2343, 2334, 3434, 3433, 2343, 2334, 3434, 3433]

In [28]:
sales_array*3

array([ 7029,  7002, 10302, 10299])

In [29]:
sales_set = {1,2,3,3,4}

In [31]:
a=np.array(sales_set)

In [34]:
sales_array[0]

2343

In [35]:
tuple1 = (1,2,3)

In [36]:
np.array(tuple1)

array([1, 2, 3])

In [39]:
sales_slice = sales_array[0:3]

In [41]:
sales_slice[0]=100

In [45]:
sales_slice

array([ 100, 2334,    0])

In [46]:
sales_copy = sales_array.copy()

In [48]:
sales_copy[0]=0

In [49]:
sales_copy

array([   0, 2334,    0, 3433])

In [50]:
sales_array

array([ 100, 2334,    0, 3433])

In [56]:
list1 = [1,2,3,4,True]

In [54]:
type(list1[5])

bool

In [57]:
np.array(list1)

array([1, 2, 3, 4, 1])

In [58]:
list(range(0,20))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [60]:
a=np.arange(0,20)

In [61]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
np.reshape(a, (5,4),'C')

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [71]:
np.reshape(a, (5,4),'F')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [72]:
sales_us = [3245,4556,5566,4434]
sales_uk = [5454,6554,3232,4434]
sales_eu = [4567,7665,5445,6776]

In [74]:
sales_matrix=np.array([sales_us,sales_uk,sales_eu])

In [76]:
profit_us = [545,444,332,344]
profit_uk=[554,565,333,434]
profit_eu=[545,222,334,433]

In [77]:
profit_matrix = np.array([profit_us,profit_uk,profit_eu])

In [83]:
profit_matrix

array([[545, 444, 332, 344],
       [554, 565, 333, 434],
       [545, 222, 334, 433]])

In [81]:
profit_matrix/sales_matrix

array([[0.16795069, 0.09745391, 0.05964786, 0.07758232],
       [0.10157682, 0.0862069 , 0.10303218, 0.09788002],
       [0.11933436, 0.02896282, 0.06134068, 0.06390201]])

In [84]:
profit_us = [545,444,332]
profit_uk=[554,565,333]
profit_eu=[545,222,334]

In [85]:
profit_matrix = np.array([profit_us,profit_uk,profit_eu])

In [87]:
profit_matrix/sales_matrix

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [88]:
profit_matrix.T

array([[545, 554, 545],
       [444, 565, 222],
       [332, 333, 334]])

In [91]:
sales_matrix

array([[3245, 4556, 5566, 4434],
       [5454, 6554, 3232, 4434],
       [4567, 7665, 5445, 6776]])

In [92]:
sales_matrix.reshape(4,3)

array([[3245, 4556, 5566],
       [4434, 5454, 6554],
       [3232, 4434, 4567],
       [7665, 5445, 6776]])

In [93]:
sales_matrix.T

array([[3245, 5454, 4567],
       [4556, 6554, 7665],
       [5566, 3232, 5445],
       [4434, 4434, 6776]])

In [99]:
sales_matrix

array([[3245, 4556, 5566, 4434],
       [5454, 6554, 3232, 4434],
       [4567,    0, 5445, 6776]])

In [98]:
sales_matrix[2,1]=0

In [100]:
qdict = {'Q1':0,'Q2':1,'Q3':2,'Q4':3}
rdict = {'US':0,'UK':1,'EU':2}

In [101]:
sales_matrix[rdict['EU']][qdict['Q2']]

0

In [102]:
stu_dict = {'stnam':'A'}

In [103]:
stu_dict['stnam']

'A'

In [104]:
import pandas as pd

In [105]:
raw_data = {'cust_id':[1,2,3,4,5],
           'cust_name':['Alex','John','Mathew','James','Johnson'],
           'Region':['N','S','N','E','W']}

In [108]:
cust_details = pd.DataFrame(raw_data)

In [110]:
type(cust_details)

pandas.core.frame.DataFrame

In [111]:
raw_data1 = {'c_id':[1,2,3,4,6],
            'Course':['Py','R','Tab','Py','R'],
            'sales':[123,323,222,122,322]}

In [112]:
raw_data1

{'c_id': [1, 2, 3, 4, 6],
 'Course': ['Py', 'R', 'Tab', 'Py', 'R'],
 'sales': [123, 323, 222, 122, 322]}

In [114]:
sales_details =pd.DataFrame(raw_data1)

In [115]:
cust_details

cust_id cust_name Region
0        1      Alex      N
1        2      John      S
2        3    Mathew      N
3        4     James      E
4        5   Johnson      W

In [116]:
sales_details

c_id Course  sales
0     1     Py    123
1     2      R    323
2     3    Tab    222
3     4     Py    122
4     6      R    322

In [123]:
pd.merge(cust_details,sales_details, left_on='cust_id', right_on='c_id',how='outer')

cust_id cust_name Region  c_id Course  sales
0      1.0      Alex      N   1.0     Py  123.0
1      2.0      John      S   2.0      R  323.0
2      3.0    Mathew      N   3.0    Tab  222.0
3      4.0     James      E   4.0     Py  122.0
4      5.0   Johnson      W   NaN    NaN    NaN
5      NaN       NaN    NaN   6.0      R  322.0

In [126]:
pd.concat([cust_details,sales_details], axis=1)

cust_id cust_name Region  c_id Course  sales
0        1      Alex      N     1     Py    123
1        2      John      S     2      R    323
2        3    Mathew      N     3    Tab    222
3        4     James      E     4     Py    122
4        5   Johnson      W     6      R    322

In [127]:
import os

In [130]:
os.getcwd()

'D:\\D\\Edureka\\Edureka - 24 June - Python\\Class 4'

In [129]:
os.chdir('D:\\D\\Edureka\\Edureka - 24 June - Python\\Class 4\\')

In [131]:
tips = pd.read_csv('tips.csv')

In [136]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [133]:
len(tips)

244

In [135]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [137]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
total_bill    244 non-null float64
tip           244 non-null float64
sex           244 non-null object
smoker        244 non-null object
day           244 non-null object
time          244 non-null object
size          244 non-null int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB


In [149]:
tips.head(4)

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2

In [143]:
tips.tail(2)

total_bill   tip     sex smoker   day    time  size
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [144]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [146]:
tips[['total_bill','sex','smoker','time']].head()

total_bill     sex smoker    time
0       16.99  Female     No  Dinner
1       10.34    Male     No  Dinner
2       21.01    Male     No  Dinner
3       23.68    Male     No  Dinner
4       24.59  Female     No  Dinner

In [148]:
tips[tips['time']=='Dinner']

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[176 rows x 7 columns]

In [154]:
female_din=tips[(tips['time']=='Dinner') & (tips['sex']=='Female')]

In [155]:
female_din

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
11        35.26  5.00  Female     No   Sun  Dinner     4
14        14.83  3.02  Female     No   Sun  Dinner     2
16        10.33  1.67  Female     No   Sun  Dinner     3
18        16.97  3.50  Female     No   Sun  Dinner     3
21        20.29  2.75  Female     No   Sat  Dinner     2
22        15.77  2.23  Female     No   Sat  Dinner     2
29        19.65  3.00  Female     No   Sat  Dinner     2
32        15.06  3.00  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
37        16.93  3.07  Female     No   Sat  Dinner     3
51        10.29  2.60  Female     No   Sun  Dinner     2
52        34.81  5.20  Female     No   Sun  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
66        16.45  2.47  Female     No   Sat  Dinner     2
67         3.07  1.00  Female    Yes   Sat  Dinner     1
71        17.07  3.00  Female     No   Sat  Dinner     3
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
74        14.73  2.20  Female     No   Sat  Dinner     2
92         5.75  1.00  Female    Yes   Fri  Dinner     2
93        16.32  4.30  Female    Yes   Fri  Dinner     2
94        22.75  3.25  Female     No   Fri  Dinner     2
100       11.35  2.50  Female    Yes   Fri  Dinner     2
101       15.38  3.00  Female    Yes   Fri  Dinner     2
102       44.30  2.50  Female    Yes   Sat  Dinner     3
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
109       14.31  4.00  Female    Yes   Sat  Dinner     2
111        7.25  1.00  Female     No   Sat  Dinner     1
114       25.71  4.00  Female     No   Sun  Dinner     3
115       17.31  3.50  Female     No   Sun  Dinner     2
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
158       13.39  2.61  Female     No   Sun  Dinner     2
162       16.21  2.00  Female     No   Sun  Dinner     3
164       17.51  3.00  Female    Yes   Sun  Dinner     2
168       10.59  1.61  Female    Yes   Sat  Dinner     2
169       10.63  2.00  Female    Yes   Sat  Dinner     2
178        9.60  4.00  Female    Yes   Sun  Dinner     2
186       20.90  3.50  Female    Yes   Sun  Dinner     3
188       18.15  3.50  Female    Yes   Sun  Dinner     3
209       12.76  2.23  Female    Yes   Sat  Dinner     2
213       13.27  2.50  Female    Yes   Sat  Dinner     2
214       28.17  6.50  Female    Yes   Sat  Dinner     3
215       12.90  1.10  Female    Yes   Sat  Dinner     2
219       30.14  3.09  Female    Yes   Sat  Dinner     4
229       22.12  2.88  Female    Yes   Sat  Dinner     2
238       35.83  4.67  Female     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [157]:
tips[(tips['size']>5) | (tips['total_bill']>45)]

total_bill    tip     sex smoker   day    time  size
59        48.27   6.73    Male     No   Sat  Dinner     4
125       29.80   4.20  Female     No  Thur   Lunch     6
141       34.30   6.70    Male     No  Thur   Lunch     6
143       27.05   5.00  Female     No  Thur   Lunch     6
156       48.17   5.00    Male     No   Sun  Dinner     6
170       50.81  10.00    Male    Yes   Sat  Dinner     3
182       45.35   3.50    Male    Yes   Sun  Dinner     3
212       48.33   9.00    Male     No   Sat  Dinner     4

In [158]:
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [159]:
tips.groupby(['smoker','sex']).size()

smoker  sex   
No      Female    54
        Male      97
Yes     Female    33
        Male      60
dtype: int64

In [160]:
tips.groupby(['smoker','day']).agg({'tip':np.mean})

tip
smoker day           
No     Fri   2.812500
       Sat   3.102889
       Sun   3.167895
       Thur  2.673778
Yes    Fri   2.714000
       Sat   2.875476
       Sun   3.516842
       Thur  3.030000