In [1]:
import os
os.chdir(r'C:\Users\Roli\Downloads')

In [2]:
import pandas as pd
import numpy as np

In [ ]:
!pip install mlxtend

In [3]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

In [4]:
df = pd.read_excel('Online_Retail.xlsx')

In [6]:
df['Description'] = df['Description'].str.strip()

In [7]:
df.dropna(axis=0, subset=['InvoiceNo'], inplace=True)

In [8]:
df['InvoiceNo'] = df['InvoiceNo'].astype('str')

In [9]:
df = df[~df['InvoiceNo'].str.contains('C')]

In [10]:
df

InvoiceNo StockCode                          Description  Quantity  \
0         536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365     71053                  WHITE METAL LANTERN         6   
2         536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...       ...                                  ...       ...   
541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587     22899          CHILDREN'S APRON DOLLY GIRL         6   
541906    581587     23254         CHILDRENS CUTLERY DOLLY GIRL         4   
541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587     22138         BAKING SET 9 PIECE RETROSPOT         3   

               InvoiceDate  UnitPrice  CustomerID         Country  
0      2010-12-01 08:26:00       2.55     17850.0  United Kingdom  
1      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
2      2010-12-01 08:26:00       2.75     17850.0  United Kingdom  
3      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
4      2010-12-01 08:26:00       3.39     17850.0  United Kingdom  
...                    ...        ...         ...             ...  
541904 2011-12-09 12:50:00       0.85     12680.0          France  
541905 2011-12-09 12:50:00       2.10     12680.0          France  
541906 2011-12-09 12:50:00       4.15     12680.0          France  
541907 2011-12-09 12:50:00       4.15     12680.0          France  
541908 2011-12-09 12:50:00       4.95     12680.0          France  

[532621 rows x 8 columns]

In [11]:
basket = (df[df['Country']=='France'].groupby(['InvoiceNo','Description'])['Quantity'].sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))

In [13]:
basket.to_csv('output1.csv')

In [14]:
def encode_units(x):
    if x<=0:
        return 0
    if x>=1:
        return 1
basket_sets = basket.applymap(encode_units)

In [15]:
basket_sets.to_csv('output2.csv')

In [16]:
basket_sets.drop('POSTAGE', inplace=True, axis=1)

In [17]:
frequent_itemsets = apriori(basket_sets, min_support=0.07, use_colnames=True)
rules = association_rules(frequent_itemsets, metric='lift', min_threshold=1)
len(rules)

26

In [18]:
rules

antecedents  \
0                         (ALARM CLOCK BAKELIKE PINK)   
1                        (ALARM CLOCK BAKELIKE GREEN)   
2                          (ALARM CLOCK BAKELIKE RED)   
3                        (ALARM CLOCK BAKELIKE GREEN)   
4                          (ALARM CLOCK BAKELIKE RED)   
5                         (ALARM CLOCK BAKELIKE PINK)   
6                                (SPACEBOY LUNCH BOX)   
7                              (DOLLY GIRL LUNCH BOX)   
8                     (PLASTERS IN TIN CIRCUS PARADE)   
9                          (PLASTERS IN TIN SPACEBOY)   
10                 (PLASTERS IN TIN WOODLAND ANIMALS)   
11                    (PLASTERS IN TIN CIRCUS PARADE)   
12                 (PLASTERS IN TIN WOODLAND ANIMALS)   
13                         (PLASTERS IN TIN SPACEBOY)   
14               (SET/20 RED RETROSPOT PAPER NAPKINS)   
15                      (SET/6 RED SPOTTY PAPER CUPS)   
16                    (SET/6 RED SPOTTY PAPER PLATES)   
17               (SET/20 RED RETROSPOT PAPER NAPKINS)   
18                    (SET/6 RED SPOTTY PAPER PLATES)   
19                      (SET/6 RED SPOTTY PAPER CUPS)   
20  (SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...   
21  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...   
22  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...   
23                    (SET/6 RED SPOTTY PAPER PLATES)   
24               (SET/20 RED RETROSPOT PAPER NAPKINS)   
25                      (SET/6 RED SPOTTY PAPER CUPS)   

                                          consequents  antecedent support  \
0                        (ALARM CLOCK BAKELIKE GREEN)            0.102041   
1                         (ALARM CLOCK BAKELIKE PINK)            0.096939   
2                        (ALARM CLOCK BAKELIKE GREEN)            0.094388   
3                          (ALARM CLOCK BAKELIKE RED)            0.096939   
4                         (ALARM CLOCK BAKELIKE PINK)            0.094388   
5                          (ALARM CLOCK BAKELIKE RED)            0.102041   
6                              (DOLLY GIRL LUNCH BOX)            0.125000   
7                                (SPACEBOY LUNCH BOX)            0.099490   
8                          (PLASTERS IN TIN SPACEBOY)            0.168367   
9                     (PLASTERS IN TIN CIRCUS PARADE)            0.137755   
10                    (PLASTERS IN TIN CIRCUS PARADE)            0.170918   
11                 (PLASTERS IN TIN WOODLAND ANIMALS)            0.168367   
12                         (PLASTERS IN TIN SPACEBOY)            0.170918   
13                 (PLASTERS IN TIN WOODLAND ANIMALS)            0.137755   
14                      (SET/6 RED SPOTTY PAPER CUPS)            0.132653   
15               (SET/20 RED RETROSPOT PAPER NAPKINS)            0.137755   
16               (SET/20 RED RETROSPOT PAPER NAPKINS)            0.127551   
17                    (SET/6 RED SPOTTY PAPER PLATES)            0.132653   
18                      (SET/6 RED SPOTTY PAPER CUPS)            0.127551   
19                    (SET/6 RED SPOTTY PAPER PLATES)            0.137755   
20                      (SET/6 RED SPOTTY PAPER CUPS)            0.102041   
21               (SET/20 RED RETROSPOT PAPER NAPKINS)            0.122449   
22                    (SET/6 RED SPOTTY PAPER PLATES)            0.102041   
23  (SET/20 RED RETROSPOT PAPER NAPKINS, SET/6 RED...            0.127551   
24  (SET/6 RED SPOTTY PAPER PLATES, SET/6 RED SPOT...            0.132653   
25  (SET/6 RED SPOTTY PAPER PLATES, SET/20 RED RET...            0.137755   

    consequent support   support  confidence      lift  leverage  conviction  
0             0.096939  0.073980    0.725000  7.478947  0.064088    3.283859  
1             0.102041  0.073980    0.763158  7.478947  0.064088    3.791383  
2             0.096939  0.079082    0.837838  8.642959  0.069932    5.568878  
3             0.094388  0.079082    0.815789  8.642959  0.069932    4.916181  
4             0.102041  0.0

In [ ]:
#Grid Search

In [19]:
os.chdir(r'F:\D\Edureka\Edureka - 24 June - Python\Class 17')

In [20]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [21]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
..        ...     ...   ...              ...        ...
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [22]:
x = dataset.iloc[:, [2,3]].values

In [23]:
x

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [25]:
x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [26]:
y = dataset.iloc[:,4].values

In [27]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [28]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.3)

In [29]:
from sklearn.svm import SVC
classifier = SVC(kernel='sigmoid')
classifier.fit(x_train, y_train)

C:\Users\Roli\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='sigmoid', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [66]:
from sklearn.neighbors import KNeighborsClassifier
classifier_knn = KNeighborsClassifier()
classifier_knn.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [31]:
y_pred_svm = classifier.predict(x_test)

In [32]:
y_pred_knn = classifier_knn.predict(x_test)

In [33]:
y_pred_svm

array([1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 1], dtype=int64)

In [34]:
y_pred_knn

array([0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0], dtype=int64)

In [37]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred_svm)
accuracy_score(y_test, y_pred_svm)

0.7583333333333333

In [38]:
from sklearn.metrics import confusion_matrix, accuracy_score
confusion_matrix(y_test, y_pred_knn)
accuracy_score(y_test, y_pred_knn)

0.9083333333333333

In [67]:
from sklearn.model_selection import GridSearchCV
parameters = [{'C':[1,2,3,4], 'kernel':['sigmoid','rbf','linear']}]
grid_search = GridSearchCV(estimator=classifier, 
                          param_grid=parameters,
                          scoring='accuracy',
                          n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

C:\Users\Roli\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
C:\Users\Roli\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [49]:
best_accuracy

0.9107142857142857

In [50]:
best_parameters

{'C': 2, 'kernel': 'rbf'}

In [71]:
n_neigh=list(range(1,21))

In [75]:
from sklearn.model_selection import GridSearchCV
parameters = [{'n_neighbors':[8,21,23]}]
grid_search = GridSearchCV(estimator=classifier_knn, 
                          param_grid=parameters,
                          scoring='accuracy',
                          n_jobs=-1)
grid_search = grid_search.fit(x_train, y_train)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_

C:\Users\Roli\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


In [76]:
best_accuracy

0.9178571428571428

In [77]:
best_parameters

{'n_neighbors': 8}

In [79]:
grid_search.best_estimator_

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=8, p=2,
                     weights='uniform')