In [ ]:
#KFold Technique
#XGBoost 
#Dimensionality Reduction

In [1]:
import os 
os.chdir('G:\\D\\Edureka\\Edureka - 24 June - Python\\Class 17\\')

In [2]:
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset

User ID  Gender   Age  EstimatedSalary  Purchased
0    15624510    Male  19.0          19000.0          0
1    15810944    Male  35.0          20000.0          0
2    15668575  Female  26.0          43000.0          0
3    15603246  Female  27.0          57000.0          0
4    15804002    Male  19.0          76000.0          0
5    15728773    Male  27.0          58000.0          0
6    15598044  Female  27.0          84000.0          0
7    15694829  Female  32.0         150000.0          1
8    15600575    Male  25.0          33000.0          0
9    15727311  Female  35.0          65000.0          0
10   15570769  Female  26.0          80000.0          0
11   15606274  Female  26.0          52000.0          0
12   15746139    Male  20.0          86000.0          0
13   15704987    Male  32.0          18000.0          0
14   15628972    Male  18.0          82000.0          0
15   15697686    Male  29.0          80000.0          0
16   15733883    Male  47.0          25000.0          1
17   15617482    Male  45.0          26000.0          1
18   15704583    Male  46.0          28000.0          1
19   15621083  Female  48.0          29000.0          1
20   15649487    Male  45.0          22000.0          1
21   15736760  Female  47.0          49000.0          1
22   15714658    Male  48.0          41000.0          1
23   15599081  Female  45.0          22000.0          1
24   15705113    Male  46.0          23000.0          1
25   15631159    Male  47.0          20000.0          1
26   15792818    Male  49.0          28000.0          1
27   15633531  Female  47.0          30000.0          1
28   15744529    Male  29.0          43000.0          0
29   15669656    Male  31.0          18000.0          0
..        ...     ...   ...              ...        ...
370  15611430  Female  60.0          46000.0          1
371  15774744    Male  60.0          83000.0          1
372  15629885  Female  39.0          73000.0          0
373  15708791    Male  59.0         130000.0          1
374  15793890  Female  37.0          80000.0          0
375  15646091  Female  46.0          32000.0          1
376  15596984  Female  46.0          74000.0          0
377  15800215  Female  42.0          53000.0          0
378  15577806    Male  41.0          87000.0          1
379  15749381  Female  58.0          23000.0          1
380  15683758    Male  42.0          64000.0          0
381  15670615    Male  48.0          33000.0          1
382  15715622  Female  44.0         139000.0          1
383  15707634    Male  49.0          28000.0          1
384  15806901  Female  57.0          33000.0          1
385  15775335    Male  56.0          60000.0          1
386  15724150  Female  49.0          39000.0          1
387  15627220    Male  39.0          71000.0          0
388  15672330    Male  47.0          34000.0          1
389  15668521  Female  48.0          35000.0          1
390  15807837    Male  48.0          33000.0          1
391  15592570    Male  47.0          23000.0          1
392  15748589  Female  45.0          45000.0          1
393  15635893    Male  60.0          42000.0          1
394  15757632  Female  39.0          59000.0          0
395  15691863  Female  46.0          41000.0          1
396  15706071    Male  51.0          23000.0          1
397  15654296  Female  50.0          20000.0          1
398  15755018    Male  36.0          33000.0          0
399  15594041  Female  49.0          36000.0          1

[400 rows x 5 columns]

In [5]:
x = dataset.iloc[:, [2,3]].values

In [6]:
x

array([[1.90e+01, 1.90e+04],
       [3.50e+01, 2.00e+04],
       [2.60e+01, 4.30e+04],
       [2.70e+01, 5.70e+04],
       [1.90e+01, 7.60e+04],
       [2.70e+01, 5.80e+04],
       [2.70e+01, 8.40e+04],
       [3.20e+01, 1.50e+05],
       [2.50e+01, 3.30e+04],
       [3.50e+01, 6.50e+04],
       [2.60e+01, 8.00e+04],
       [2.60e+01, 5.20e+04],
       [2.00e+01, 8.60e+04],
       [3.20e+01, 1.80e+04],
       [1.80e+01, 8.20e+04],
       [2.90e+01, 8.00e+04],
       [4.70e+01, 2.50e+04],
       [4.50e+01, 2.60e+04],
       [4.60e+01, 2.80e+04],
       [4.80e+01, 2.90e+04],
       [4.50e+01, 2.20e+04],
       [4.70e+01, 4.90e+04],
       [4.80e+01, 4.10e+04],
       [4.50e+01, 2.20e+04],
       [4.60e+01, 2.30e+04],
       [4.70e+01, 2.00e+04],
       [4.90e+01, 2.80e+04],
       [4.70e+01, 3.00e+04],
       [2.90e+01, 4.30e+04],
       [3.10e+01, 1.80e+04],
       [3.10e+01, 7.40e+04],
       [2.70e+01, 1.37e+05],
       [2.10e+01, 1.60e+04],
       [2.80e+01, 4.40e+04],
       [2.70e+

In [7]:
y = dataset.iloc[:,4].values

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1,

In [9]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x = sc.fit_transform(x)

In [10]:
x

array([[-1.78179743, -1.49004624],
       [-0.25358736, -1.46068138],
       [-1.11320552, -0.78528968],
       [-1.01769239, -0.37418169],
       [-1.78179743,  0.18375059],
       [-1.01769239, -0.34481683],
       [-1.01769239,  0.41866944],
       [-0.54012675,  2.35674998],
       [-1.20871865, -1.07893824],
       [-0.25358736, -0.13926283],
       [-1.11320552,  0.30121002],
       [-1.11320552, -0.52100597],
       [-1.6862843 ,  0.47739916],
       [-0.54012675, -1.51941109],
       [-1.87731056,  0.35993973],
       [-0.82666613,  0.30121002],
       [ 0.89257019, -1.3138571 ],
       [ 0.70154394, -1.28449224],
       [ 0.79705706, -1.22576253],
       [ 0.98808332, -1.19639767],
       [ 0.70154394, -1.40195167],
       [ 0.89257019, -0.60910054],
       [ 0.98808332, -0.84401939],
       [ 0.70154394, -1.40195167],
       [ 0.79705706, -1.37258681],
       [ 0.89257019, -1.46068138],
       [ 1.08359645, -1.22576253],
       [ 0.89257019, -1.16703281],
       [-0.82666613,

In [11]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [12]:
from sklearn.svm import SVC
classifier = SVC(kernel='rbf')
classifier.fit(x_train,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [13]:
y_pred = classifier.predict(x_test)

In [14]:
y_pred

array([0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0], dtype=int64)

In [16]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)

In [17]:
(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])

0.875

In [19]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=x_train, y=y_train, cv=10)
accuracies.mean()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)
C:\Users\HP\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The defa

0.912414467253177

In [21]:
accuracies.mean()

0.912414467253177

In [23]:
accuracies.std()

0.058592672176149795

# Extreme Gradient Boosting

In [24]:
dataset = pd.read_csv('Churn_Modelling.csv')

In [26]:
x = dataset.iloc[:,3:13].values

In [27]:
y = dataset.iloc[:,13].values

In [28]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [29]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [30]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_1 = LabelEncoder()
x[:,1] = labelencoder_x_1.fit_transform(x[:,1])

In [31]:
x

array([[619, 0, 'Female', ..., 1, 1, 101348.88],
       [608, 2, 'Female', ..., 0, 1, 112542.58],
       [502, 0, 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 0, 'Female', ..., 0, 1, 42085.58],
       [772, 1, 'Male', ..., 1, 0, 92888.52],
       [792, 0, 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [32]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x_2 = LabelEncoder()
x[:,2] = labelencoder_x_2.fit_transform(x[:,2])

In [34]:
onehotencoder = OneHotEncoder(categorical_features=[1])
x = onehotencoder.fit_transform(x).toarray()

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)


In [36]:
pd.DataFrame(x)

0    1    2      3    4     5     6          7    8    9    10  \
0     1.0  0.0  0.0  619.0  0.0  42.0   2.0       0.00  1.0  1.0  1.0   
1     0.0  0.0  1.0  608.0  0.0  41.0   1.0   83807.86  1.0  0.0  1.0   
2     1.0  0.0  0.0  502.0  0.0  42.0   8.0  159660.80  3.0  1.0  0.0   
3     1.0  0.0  0.0  699.0  0.0  39.0   1.0       0.00  2.0  0.0  0.0   
4     0.0  0.0  1.0  850.0  0.0  43.0   2.0  125510.82  1.0  1.0  1.0   
5     0.0  0.0  1.0  645.0  1.0  44.0   8.0  113755.78  2.0  1.0  0.0   
6     1.0  0.0  0.0  822.0  1.0  50.0   7.0       0.00  2.0  1.0  1.0   
7     0.0  1.0  0.0  376.0  0.0  29.0   4.0  115046.74  4.0  1.0  0.0   
8     1.0  0.0  0.0  501.0  1.0  44.0   4.0  142051.07  2.0  0.0  1.0   
9     1.0  0.0  0.0  684.0  1.0  27.0   2.0  134603.88  1.0  1.0  1.0   
10    1.0  0.0  0.0  528.0  1.0  31.0   6.0  102016.72  2.0  0.0  0.0   
11    0.0  0.0  1.0  497.0  1.0  24.0   3.0       0.00  2.0  1.0  0.0   
12    1.0  0.0  0.0  476.0  0.0  34.0  10.0       0.00  2.0  1.0  0.0   
13    1.0  0.0  0.0  549.0  0.0  25.0   5.0       0.00  2.0  0.0  0.0   
14    0.0  0.0  1.0  635.0  0.0  35.0   7.0       0.00  2.0  1.0  1.0   
15    0.0  1.0  0.0  616.0  1.0  45.0   3.0  143129.41  2.0  0.0  1.0   
16    0.0  1.0  0.0  653.0  1.0  58.0   1.0  132602.88  1.0  1.0  0.0   
17    0.0  0.0  1.0  549.0  0.0  24.0   9.0       0.00  2.0  1.0  1.0   
18    0.0  0.0  1.0  587.0  1.0  45.0   6.0       0.00  1.0  0.0  0.0   
19    1.0  0.0  0.0  726.0  0.0  24.0   6.0       0.00  2.0  1.0  1.0   
20    1.0  0.0  0.0  732.0  1.0  41.0   8.0       0.00  2.0  1.0  1.0   
21    0.0  0.0  1.0  636.0  0.0  32.0   8.0       0.00  2.0  1.0  0.0   
22    0.0  0.0  1.0  510.0  0.0  38.0   4.0       0.00  1.0  1.0  0.0   
23    1.0  0.0  0.0  669.0  1.0  46.0   3.0       0.00  2.0  0.0  1.0   
24    1.0  0.0  0.0  846.0  0.0  38.0   5.0       0.00  1.0  1.0  1.0   
25    1.0  0.0  0.0  577.0  1.0  25.0   3.0       0.00  2.0  0.0  1.0   
26    0.0  1.0  0.0  756.0  1.0  36.0   2.0  136815.64  1.0  1.0  1.0   
27    1.0  0.0  0.0  571.0  1.0  44.0   9.0       0.00  2.0  0.0  0.0   
28    0.0  1.0  0.0  574.0  0.0  43.0   3.0  141349.43  1.0  1.0  1.0   
29    1.0  0.0  0.0  411.0  1.0  29.0   0.0   59697.17  2.0  1.0  1.0   
...   ...  ...  ...    ...  ...   ...   ...        ...  ...  ...  ...   
9970  1.0  0.0  0.0  518.0  1.0  42.0   7.0  151027.05  2.0  1.0  0.0   
9971  1.0  0.0  0.0  833.0  0.0  34.0   3.0  144751.81  1.0  0.0  0.0   
9972  1.0  0.0  0.0  758.0  1.0  26.0   4.0  155739.76  1.0  1.0  0.0   
9973  1.0  0.0  0.0  611.0  1.0  27.0   7.0       0.00  2.0  1.0  1.0   
9974  1.0  0.0  0.0  583.0  1.0  33.0   7.0  122531.86  1.0  1.0  0.0   
9975  0.0  1.0  0.0  610.0  1.0  50.0   1.0  113957.01  2.0  1.0  0.0   
9976  1.0  0.0  0.0  637.0  0.0  33.0   7.0  103377.81  1.0  1.0  0.0   
9977  1.0  0.0  0.0  683.0  0.0  32.0   9.0       0.00  2.0  1.0  1.0   
9978  1.0  0.0  0.0  774.0  1.0  40.0   9.0   93017.47  2.0  1.0  0.0   
9979  1.0  0.0  0.0  677.0  0.0  58.0   1.0   90022.85  1.0  0.0  1.0   
9980  0.0  0.0  1.0  741.0  1.0  35.0   6.0   74371.49  1.0  0.0  0.0   
9981  0.0  1.0  0.0  498.0  1.0  42.0   3.0  152039.70  1.0  1.0  1.0   
9982  0.0  1.0  0.0  655.0  0.0  46.0   7.0  137145.12  1.0  1.0  0.0   
9983  1.0  0.0  0.0  613.0  1.0  40.0   4.0       0.00  1.0  0.0  0.0   
9984  0.0  1.0  0.0  602.0  1.0  35.0   7.0   90602.42  2.0  1.0  1.0   
9985  1.0  0.0  0.0  659.0  1.0  36.0   6.0  123841.49  2.0  1.0  0.0   
9986  0.0  1.0  0.0  673.0  1.0  47.0   1.0  183579.54  2.0  0.0  1.0   
9987  0.0  0.0  1.0  606.0  1.0  30.0   8.0  180307.73  2.0  1.0  1.0   
9988  1.0  0.0  0.0  775.0  1.0  30.0   4.0       0.00  2.0  1.0  0.0   
9989  0.0  0.0  1.0  841.0  1.0  28.0   4.0       0.00  2.0  1.0  1.0   
9990  0.0  1.0  0.0  714.0  1.0  33.0   3.0   35016.60  1.0  1.0  0.0   
9991  1.0  0.0  0.0  597.0  0.0  53.0   4.0   88381.21  1.0  1.0  0.0   
9992  0.0  0.0  1.0  726.0  1.0  36.0   2.0       0.00  1.0  1.0 

In [37]:
x = x[:,1:]

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [47]:
from xgboost import XGBClassifier
classifier = XGBClassifier()
classifier.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
              max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
              n_jobs=1, nthread=None, objective='binary:logistic',
              random_state=0, reg_alpha=0, reg_lambda=1, scale_pos_weight=1,
              seed=None, silent=True, subsample=1)

In [40]:
y_pred = classifier.predict(x_test)

In [42]:
cm=confusion_matrix(y_test,y_pred)

In [43]:
(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])

0.864

In [44]:
from sklearn.model_selection import cross_val_score
accuracies = cross_val_score(estimator=classifier, X=x_train, y=y_train, cv =10)
accuracies.mean()

0.8639954523366443

In [45]:
accuracies.std()

0.012429267521996839

In [46]:
accuracies

array([0.87765293, 0.8639201 , 0.86017478, 0.8639201 , 0.88125   ,
       0.86375   , 0.87234043, 0.83354193, 0.85732165, 0.8660826 ])

In [ ]:
#XGBoost for regression

# Dimensionality Reduction

In [49]:
os.chdir('G:\\D\\Edureka\\Edureka - 24 June - Python\\Class 16\\')

In [50]:
dataset = pd.read_csv('Bank-data.csv')

In [51]:
dataset

Index  interest_rate  credit  Gender  previous  duration Churn
0        0          1.334       0       1         0       117    no
1        1          0.767       0       0         1       274   yes
2        2          4.858       0       1         0       167    no
3        3          4.120       0       0         0       686   yes
4        4          4.856       0       1         0       159    no
5        5          0.899       0       0         0       120    no
6        6          4.962       0       0         0       337    no
7        7          4.858       0       1         0       640    no
8        8          4.962       0       0         0       663   yes
9        9          4.865       0       0         0       403    no
10      10          1.365       0       0         1       300    no
11      11          4.962       0       0         0       255   yes
12      12          4.858       0       0         1       293   yes
13      13          4.962       0       0         0        68    no
14      14          4.865       0       0         0       266    no
15      15          1.334       0       0         0       266   yes
16      16          0.767       0       0         1       159   yes
17      17          4.858       1       1         0       120   yes
18      18          4.120       0       1         0       337   yes
19      19          4.856       0       0         0       640    no
20      20          0.899       0       0         0       663   yes
21      21          4.962       0       0         1       403   yes
22      22          4.858       0       1         0       300    no
23      23          4.962       0       0         0       255   yes
24      24          4.865       0       1         1       293   yes
25      25          1.365       0       1         0        68    no
26      26          4.962       0       0         0       266   yes
27      27          4.858       0       0         0       272   yes
28      28          4.962       0       0         0       398   yes
29      29          4.865       0       0         0       126    no
..     ...            ...     ...     ...       ...       ...   ...
488    488          0.885       0       0         1       608   yes
489    489          4.153       0       0         0       250    no
490    490          0.735       0       0         0       107   yes
491    491          4.965       0       0         0       716   yes
492    492          4.859       0       1         0       619   yes
493    493          4.864       0       0         0       406    no
494    494          4.963       0       0         0        73    no
495    495          1.334       0       1         0       127    no
496    496          4.153       0       0         0       187    no
497    497          0.646       1       0         1       180   yes
498    498          1.266       0       1         0       326   yes
499    499          1.405       0       0         0       109   yes
500    500          0.900       0       0         1       470   yes
501    501          4.076       0       0         0        73    no
502    502          1.050       0       0         0       141    no
503    503          1.029       0       0         0       115    no
504    504          0.748       0       0         1       171    no
505    505          4.961       0       0         0       498    no
506    506          1.268       0       0         0       365   yes
507    507          4.959       0       0         0        10    no
508    508          4.021       0       0         0       796   yes
509    509          0.877       0       0         1       279   yes
510    510          1.327       0       1         0       476   yes
511    511          4.965       0       0         0       479   yes
512    512          1.266       0       1         0       225    no
513    513          1.334       0       1         0       204    no
514    514          0.861       0       0         1       806

In [52]:
dataset['Churn'] = dataset['Churn'].astype('category')
dataset['Churn'] = dataset['Churn'].cat.codes

In [55]:
x=dataset.iloc[:,0:6].values

In [56]:
y = dataset.iloc[:,6].values

In [57]:
y

array([0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,

In [58]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [59]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [60]:
y_pred = logmodel.predict(x_test)

In [62]:
cm=confusion_matrix(y_test,y_pred)

In [63]:
(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])

0.8076923076923077

In [64]:
from sklearn.decomposition import PCA
#Principal component Analysis
pca = PCA(n_components=None)
x_train_n = pca.fit_transform(x_train)
x_test_n = pca.fit_transform(x_test)

In [69]:
len(x_train)

414

In [68]:
len(x_train_n)

414

In [81]:
from sklearn.decomposition import PCA
#Principal component Analysis
pca = PCA(n_components=2)
x_train_2 = pca.fit_transform(x_train)
x_test_2= pca.fit_transform(x_test)

In [72]:
pd.DataFrame(x_train_n)

0           1         2         3         4         5
0   -112.098061  172.977078  2.201199 -0.287630 -0.287470 -0.081058
1    207.203725  167.288700  2.012707 -0.303140 -0.278577 -0.076299
2    -66.586378   53.253614  2.190009 -0.395099  0.696451 -0.107917
3    -29.287139  146.381587  1.267371 -0.449960  0.800277  0.889221
4    759.273676  104.366719 -2.125078 -0.289536 -0.020850 -0.021902
5    -15.736655 -249.391651  1.555409 -0.215242 -0.280381 -0.023098
6    335.761836  150.031650  1.583874  0.687214 -0.125361 -0.029424
7   -280.609965  188.068305  1.726286  0.714326 -0.126034 -0.039539
8    117.177194 -244.511621 -2.142365 -0.193220 -0.041953  0.015816
9   -126.699336   90.517070 -2.043360 -0.237789 -0.019350 -0.026950
10    69.902124    4.214332  1.592807 -0.263934 -0.263251 -0.053292
11  -152.546456 -189.355992 -2.005370 -0.188582 -0.043994  0.005998
12  -102.116318  242.298603 -1.840136 -0.392459  0.972633 -0.088699
13  -222.049588 -207.391881  1.455168 -0.209978 -0.268693 -0.028443
14  -312.921704  -75.985865 -2.059799 -0.198545 -0.029963 -0.008069
15  -316.021072   -4.046364  1.638140  0.750039 -0.135404 -0.015846
16  -167.761259  126.333855  1.338421 -0.313731 -0.197883  0.931579
17   243.981354   38.307557 -1.992687 -0.250176 -0.030114 -0.018778
18    89.043684 -240.331555  1.976252 -0.351721  0.685377 -0.069499
19   137.252448   -6.824920 -1.992053 -0.236403 -0.032818 -0.014085
20   676.842295  117.967281  1.603452  0.673295 -0.132235 -0.023536
21   -48.224717 -130.288617  1.449990 -0.232993 -0.263732 -0.036474
22  -280.423837  -24.015793 -2.049050 -0.209393 -0.026786 -0.014191
23  -125.345583 -161.551560  1.587465 -0.224398 -0.274442 -0.034675
24  -216.361473  111.910873 -1.903425  0.753583  0.102112  0.007914
25  -193.921801 -108.528495 -2.073912 -0.199562 -0.032717 -0.003239
26  -164.367640  181.456005  2.128841 -0.285540 -0.281644 -0.081663
27   166.407756  -45.991798  1.555762  0.730671 -0.137734 -0.006775
28  -221.526634  151.777030 -2.016081 -0.243176 -0.015363 -0.035197
29  -330.880743  196.606056 -1.152950 -0.251786 -0.066636 -0.050303
..          ...         ...       ...       ...       ...       ...
384 -158.493370 -225.544838 -2.109007 -0.181181 -0.040135  0.011375
385 -224.595471 -154.442640 -1.964898  0.800290  0.084828  0.040398
386 -141.755268 -182.037940 -1.978051  0.800457  0.082730  0.044387
387 -235.942190  234.390588  2.254160 -0.417165  0.708319 -0.131397
388 -183.033342   66.863747 -2.038995 -0.230581 -0.021025 -0.024535
389 -201.785745  -44.731692  1.588550 -0.365698  0.728718 -0.090795
390  627.658514  123.535672 -2.105787 -0.285552 -0.019390 -0.025268
391  -63.968882  -70.722397  1.617048  0.747426 -0.141626 -0.005976
392  146.684562 -158.615412  2.010285 -0.369288  0.689207 -0.079259
393  354.316207  165.579191  2.165507 -0.312410 -0.289911 -0.076718
394  146.754702  147.517083  1.639238 -0.293263 -0.255461 -0.070430
395  889.741829  -46.892587  1.479671  0.690596 -0.139330 -0.001094
396  -33.773352  197.272186  2.325839  0.568332  0.826909 -0.086885
397  -27.589467  -14.637484  1.487864 -0.254329 -0.257103 -0.050583
398 -186.483189  150.798829 -2.021982 -0.244939 -0.015372 -0.034787
399  752.996150  -91.899764 -2.051816  0.735049  0.086748  0.040275
400   72.352456  -79.750155  2.195194 -0.380150  0.684224 -0.091126
401    8.099391  236.511148 -1.956826 -0.396732  0.978736 -0.086060
402 -208.082621  -68.925818  2.231138 -0.366465  0.685265 -0.094650
403 -329.705793  190.636883  2.305643 -0.404779  0.702319 -0.127315
404 -329.622704  -86.477356 -1.944959  0.794387  0.089918  0.031357
405  376.211095  135.205939 -2.085658 -0.273520 -0.017516 -0.028537
406 -272.997066  -72.819920 -2.063247 -0.201315 -0.029842 -0.008149
407 -176.463904 -261.084848  1.520436  0.787261 -0.149621  0.017086
408 -310.084018 -138.930792  1.831661 -0.219854 -0.286782 -0.041155
409 -303.777221   56.336475  1.671942  0.738702 -0.132863 -0.023349
410 -120.650962   54.677381  1.645562 -0.262270 -0.260923 -0.061145
41

In [73]:
pd.DataFrame(x_train_2)

0           1
0   -112.098061  172.977078
1    207.203725  167.288700
2    -66.586378   53.253614
3    -29.287139  146.381587
4    759.273676  104.366719
5    -15.736655 -249.391651
6    335.761836  150.031650
7   -280.609965  188.068305
8    117.177194 -244.511621
9   -126.699336   90.517070
10    69.902124    4.214332
11  -152.546456 -189.355992
12  -102.116318  242.298603
13  -222.049588 -207.391881
14  -312.921704  -75.985865
15  -316.021072   -4.046364
16  -167.761259  126.333855
17   243.981354   38.307557
18    89.043684 -240.331555
19   137.252448   -6.824920
20   676.842295  117.967281
21   -48.224717 -130.288617
22  -280.423837  -24.015793
23  -125.345583 -161.551560
24  -216.361473  111.910873
25  -193.921801 -108.528495
26  -164.367640  181.456005
27   166.407756  -45.991798
28  -221.526634  151.777030
29  -330.880743  196.606056
..          ...         ...
384 -158.493370 -225.544838
385 -224.595471 -154.442640
386 -141.755268 -182.037940
387 -235.942190  234.390588
388 -183.033342   66.863747
389 -201.785745  -44.731692
390  627.658514  123.535672
391  -63.968882  -70.722397
392  146.684562 -158.615412
393  354.316207  165.579191
394  146.754702  147.517083
395  889.741829  -46.892587
396  -33.773352  197.272186
397  -27.589467  -14.637484
398 -186.483189  150.798829
399  752.996150  -91.899764
400   72.352456  -79.750155
401    8.099391  236.511148
402 -208.082621  -68.925818
403 -329.705793  190.636883
404 -329.622704  -86.477356
405  376.211095  135.205939
406 -272.997066  -72.819920
407 -176.463904 -261.084848
408 -310.084018 -138.930792
409 -303.777221   56.336475
410 -120.650962   54.677381
411 -200.920401 -245.792057
412 -234.886416   95.362689
413 -139.611628  190.181826

[414 rows x 2 columns]

In [77]:
explained_variance = pca.explained_variance_ratio_

In [78]:
explained_variance

array([8.27819027e-01, 1.72147481e-01, 3.05795279e-05, 1.77484639e-06,
       7.72964764e-07, 3.63889822e-07])

In [82]:
pd.DataFrame(x_train_2)

0           1
0   -112.098061  172.977078
1    207.203725  167.288700
2    -66.586378   53.253614
3    -29.287139  146.381587
4    759.273676  104.366719
5    -15.736655 -249.391651
6    335.761836  150.031650
7   -280.609965  188.068305
8    117.177194 -244.511621
9   -126.699336   90.517070
10    69.902124    4.214332
11  -152.546456 -189.355992
12  -102.116318  242.298603
13  -222.049588 -207.391881
14  -312.921704  -75.985865
15  -316.021072   -4.046364
16  -167.761259  126.333855
17   243.981354   38.307557
18    89.043684 -240.331555
19   137.252448   -6.824920
20   676.842295  117.967281
21   -48.224717 -130.288617
22  -280.423837  -24.015793
23  -125.345583 -161.551560
24  -216.361473  111.910873
25  -193.921801 -108.528495
26  -164.367640  181.456005
27   166.407756  -45.991798
28  -221.526634  151.777030
29  -330.880743  196.606056
..          ...         ...
384 -158.493370 -225.544838
385 -224.595471 -154.442640
386 -141.755268 -182.037940
387 -235.942190  234.390588
388 -183.033342   66.863747
389 -201.785745  -44.731692
390  627.658514  123.535672
391  -63.968882  -70.722397
392  146.684562 -158.615412
393  354.316207  165.579191
394  146.754702  147.517083
395  889.741829  -46.892587
396  -33.773352  197.272186
397  -27.589467  -14.637484
398 -186.483189  150.798829
399  752.996150  -91.899764
400   72.352456  -79.750155
401    8.099391  236.511148
402 -208.082621  -68.925818
403 -329.705793  190.636883
404 -329.622704  -86.477356
405  376.211095  135.205939
406 -272.997066  -72.819920
407 -176.463904 -261.084848
408 -310.084018 -138.930792
409 -303.777221   56.336475
410 -120.650962   54.677381
411 -200.920401 -245.792057
412 -234.886416   95.362689
413 -139.611628  190.181826

[414 rows x 2 columns]

In [83]:
from sklearn.linear_model import LogisticRegression
logmodel = LogisticRegression()
logmodel.fit(x_train_2,y_train)

C:\Users\HP\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [84]:
y_pred = logmodel.predict(x_test_2)

In [87]:
cm=confusion_matrix(y_test,y_pred)

In [88]:
(cm[0,0]+cm[1,1])/(cm[0,0]+cm[0,1]+cm[1,0]+cm[1,1])

0.6923076923076923